### ISSUE TITLE
[쿠버네티스] 오브젝트

### ISSUE THREAD

**Issue by backtony** [backtony/blog-code#2]
## 도커
+ 컨테이너로 가상화해서 배포를 쉽게 해주는 기술

## 쿠버네티스
도커는 하나의 서비스를 컨테이너로 가상화시켜서 배포하는 것이지 엄청 많은 서비스들을 운영할 때 그걸 일일이 배포하고 운영하는 역할을 제공하지는 않는다. 이런 기능을 제공하는 것을 __컨테이너 오케스트레이터__ 라고 하는데 여러 컨테이너들을 관리해주는 솔루션이다. 여러 솔루션이 나왔지만 커버네티스가 표준으로 자리잡았다.

## 미리보기
![1](https://media.oss.navercorp.com/user/32533/files/f0aef247-d3b5-4adb-84dc-9d88bf210542)

+ 서버 한 대는 마스터로 쓰고 다른 서버는 노드라고 표현해서 하나의 마스터에 여러 노드들이 연결된다. 연결되면 이것이 하나의 클러스터라는 개념으로 묶인다.  
+ 마스터는 전반적인 컨트롤 역할이고 노드들은 자원을 제공하는 역할을 한다. 자원을 늘리고 싶다면 노드들을 추가하면 된다.  
+ 쿠버네티스 클러스터 안에서 네임스페이스가 쿠버네티스 오브젝트들을 독립된 공간으로 분리한다. 네임스페이스에는 쿠버네티스 최소 배포단위인 pod가 존재하고 pod들에게 외부로 연결 가능하도록 ip를 할당해주는 service가 있다. 참고로 서로 다른 네임스페이스에는 연결할 수 없다.(가능하나 보통 전략으로 막는다.)  
+ 파드에는 여러 앱(컨테이너)들이 돌아간다. 
+ 문제가 생기면 다 날라가기 때문에 volume을 만들어 연결시켜두고 데이터를 별도로 저장한다.
+ 네임스페이스에 ResourceQuota와 LimitRange 을 달아서 한 네임스페이스에 사용가능한 자원을 한정시킬 수 있다.
+ pod 생성시 컨테이너 안에 환경 변수 값을 넣는다던가 파일을 마운팅해줄 수 있는데 ConfigMap, Secret을 통해 가능하다.

<br>

![2](https://media.oss.navercorp.com/user/32533/files/0db3577d-6968-4e9c-b9a1-f708a99402f6)

컨트롤러가 pod들을 관리해주는데 controller의 종류가 여럿 있다.
+ Replication Controller, ReplicaSet
    - 파드가 죽으면 감지해서 다시 살려준다든지 파드의 개수를 늘렸다가 줄인다든가의 기능을 한다.
+ Deployment
    - 배포 후의 파드들을 새 버전으로 업그레이드 한다.
    - 업그레이드 도중에 문제가 생기면 롤백을 도와준다.
+ DaemonSet
    - 한 노드에 파드가 하나씩만 유지가 되도록 해준다.
    - 이런 기능이 필요한 모듈들이 있다.
+ CronJob
    - Job은 어떤 특정 작업만 하고 종료시켜야하는 일을 할때 파드가 그렇게 동작을 하도록 해준다.
    - 이런 일을 주기적으로 실행해야 할 때 CronJob을 사용한다.

## Pod
![3](https://media.oss.navercorp.com/user/32533/files/a505c66a-f12d-45ad-9144-404ec2a859fc)

+ Pod 안에는 하나의 독립적인 서비스를 구동할 수 있는 컨테이너들이 있다.
+ 컨테이너들은 서비스가 연결될 수 있도록 포트가 존재한다. 
+ 한 파드 내에서 포트가 중복될 수는 없다.
+ 파드가 생성될 때 고유의 IP가 할당되는데 쿠버네티스 클러스터 내에서만 해당 IP로 해당 파드에 접근할 수 있다. 외부에서는 해당 IP로 접속할 수 없다.
+ 문제 발생 시 재생성되는데 이때 IP는 다른 것이 재할당된다.(휘발성)

```yml
apiVersion: v1
kind: Pod # pod를 만들거다.
metadata:
  name: pod-1 # 이름
spec:
  containers: # 파드 안의 컨테이너를 정의한다. - 2개의 컨테이너 정의
  - name: container1
    image: kubetm/p8000
    ports:
    - containerPort: 8000 # 포트
  - name: container2
    image: kubetm/p8080
    ports:
    - containerPort: 8080 
```

## Label
![4](https://media.oss.navercorp.com/user/32533/files/027dbca6-1de4-4d4e-8e32-8013f2a412c7)

+ 파드뿐만 아니라 모든 오브젝트에 라벨을 달 수 있다. 보통 파드에서 가장 많이 사용한다.
+ 라벨을 사용하는 이유는 목적에 따라 오브젝트들을 분류하고 그 분류된 오브젝트들만 분류해서 따로 연결하기 위해 사용
+ key:value 형태의 한쌍으로 구성된다.
+ 한 파드에는 여러 개의 라벨을 달 수 있다.
+ 웹 화면만 보고 싶다면 type이 web인 파드만 서비스에 연결해서 서비스 정보만 알려주면 되고, 서비스 담당 운영자면 lo:production 라벨이 달린 파드만 서비스에 연결해서 서비스 정보를 운영자에게 알려주면 된다.

```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels: # 파드에 라벨 주기
    type: web
    lo: dev
spec:
  containers:
  - name: container
    image: kubetm/init
```
추후 서비스를 만들 때
```yml
apiVersion: v1
kind: Service
metadata:
  name: svc-1
spec:
  selector:
    type: web # 라벨 연결
  ports:
  - port: 8080
```

## Node Schedule
![5](https://media.oss.navercorp.com/user/32533/files/8e928beb-fb8a-49a2-b9bb-e3c474fc1b83)

+ 파드는 결국 여러 노드 중 한 노드에 올라가야 한다.
+ 직접 선택하는 방법과 쿠버네티스가 선택해주는 방법이 있다.

```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  nodeSelector: # 노드 직접 지정 -> 노드 라벨을 적어주면 된다.
    hostname: k8s-node1 
  containers:
  - name: container
    image: kubetm/init
```
파드에 라벨을 다는 것처럼 노드에 라벨을 달고 파드를 만들 때 노드를 지정할 수 있다.

<br>

쿠버네티스의 스케줄러가 판단하는 방법은 다음과 같다.
```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-4
spec:
  containers:
  - name: container
    image: kubetm/init
    resources: # 리소스 지정
      requests:
        memory: 2Gi # 메모리 최소 요구
      limits:
        memory: 3Gi # 최대 메모리 요구
```
+ 노드에는 사용 가능한 자원(CPU, 메모리)가 있기 때문에 이를 판단하여 선택한다.  
+ 메모리의 경우 limit을 넘으면 파드를 바로 종료
+ cpu 초과시 request를 낮추고 over시 종료되지는 않음

### ClusterIp
![6](https://media.oss.navercorp.com/user/32533/files/a4e4bd86-16e8-47fe-ac51-a8ed55c65ad9)

+ 서비스는 자신의 클러스터 ip를 가지고 있다.
+ 이 서비스를 파드에 연결시켜두면 서비스의 ip를 통해서 파드에 접근할 수 있다.
+ 파드에도 똑같이 클러스터에서 접근할 수 있는 ip가 있는데 굳이 서비스로 연결해서 사용할까?
  - 파드는 언제든지 장애로 죽을 수 있고 재생성될 수 있는 오브젝트다. 재생성 시 파드의 ip는 변한다. 
  - 하지만 서비스는 사용자가 지우지 않는한 삭제되거나 재생성되지 않는다.
  - 따라서 서비스로 접근하면 항상 살아있는 파드에 접근할 수 있다.  
+ 서비스의 종류에는 여러 개가 있는데 가장 기본적인 방식이 클러스터 IP 방식이다. ip는 클러스터 내에서만 접근할 수 있는 ip로 클러스터 내부에서는 접근 가능하지만 외부에서는 접근할 수 없다.
+ 파드를 여러 개 연결할 수 있는데 트래픽을 분산해주는 역할을 해준다.(로드밸런스)

```yml
apiVersion: v1
kind: Service
metadata:
  name: svc-2
spec:
  selector: # 연결 파드 라벨 지정
    app: pod
  ports:
  - port: 9000 # 9000번 포트로 들어오면
    targetPort: 8080 # 파드의 8080포트로 연결한다.
  type: ClusterIp # service 타입지정
```
타입을 생략하면 ClusterIp가 디폴트로 동작한다.

사용 용도
+ 외부에서 접근 불가능, 내부에서만 접근 가능
+ 따라서 접근 가능한 대상은 클러스터 내부에 접근 가능한 운영자
+ 주된 작업은 쿠버네티스 대시보드 관리, 각 파드의 서비스 디버깅 용도

### NodePort
![스크린샷 2022-07-07 오전 12 36 09](https://media.oss.navercorp.com/user/32533/files/6a16bf27-c025-4faf-bef2-c5585d375be6)

노드 포트 타입으로 만들어도 서비스에는 기본적으로 ClusterIp가 할당되어 기본적으로 ClusterIp 기능을 가지고 있다.
쿠버네티스 클러스터에 연결되어 있는 모든 노드에 똑같은 포트가 할당이 되어 외부에서 어느 노드건 간에 포트로 연결하면 서비스로 연결되고 서비스는 연결된 파드에 트래픽을 전달한다.
특이점은 파드가 있는 노드에만 포트가 만들어지는게 아니라 모든 노드에 포트가 만들어진다.
```yml
apiVersion: v1
kind: Service
metadata:
  name: svc-2
spec:
  selector:
    app: pod
  ports:
  - port: 9000
    targetPort: 8080
    nodePort: 30000 # 노드 포트 지정
  type: NodePort # 서비스 타입
  externalTrafficPolicy: Local # 트래픽 전달 전략
```
노드 포트는 30000~32767 사이의 값이어야 하고 작성하지 않으면 그 중 하나가 된다.
특이점은 1번 노드에 접근하더라도 서비스는 연결된 아무 파드에나 트래픽을 전달하는데 이 또한 옵션으로 들어온 노드로 트래픽을 전달할 수 있다. 이 옵션이 externalTrafficPolicy: Local이다.

사용 용도
+ 물리적인 호스트(노드)의 IP를 통해서 파드에 접근 가능
+ 대부분 호스트 IP는 내부망에서만 접근 가능하도록 보안적으로 구성함
+ 노드 포트는 클러스터 밖에는 있지만 보통 내부에서 접근해야할 때 사용

### Load Balancer
![스크린샷 2022-07-07 오전 12 36 16](https://media.oss.navercorp.com/user/32533/files/43d9bf59-e781-417e-903a-f789ca7413e2)

기본적으로 nodePort의 성격을 그대로 가져온다.
추가적으로 로드밸런서가 생겨서 각 노드에 트래픽을 분산시켜주는 역할을 한다.
한 가지 문제가, 이 로드밸런서로 접근하기 위한 외부 접속 ip주소는 별도로 외부 접속 ip를 할당해주는 플러그인이 설치가 되어 있어야 생긴다. 
만약 구글 클라우드 플랫폼이나 아마존에서 제공하는 쿠버네티스 플랫폼을 사용하면 자체적으로 플러그인이 설치가 되어있어서 로드밸런서 타입으로 만들면 외부에서 접속할 수 있는 ip를 만들어준다. 
이를 통해 외부에서 접근이 가능해진다.

```yml
apiVersion: v1
kind: Service
metadata:
  name: svc-3
spec:
  selector:
    app: pod
  ports:
  - port: 9000
    targetPort: 8080
  type: LoadBalancer # 타입 지정
```

사용 용도
+ 실제적으로 외부에 서비스 노출시키려면 로드밸런서 사용
+ 내부 ip 노출 없이 외부 ip를 통해 안정적으로 서비스 노출

### emptyDir
![스크린샷 2022-07-06 오후 10 36 41](https://media.oss.navercorp.com/user/32533/files/82a797eb-b8c4-4654-857b-5e3be849b5f0)

컨테이너들끼리 데이터를 공유하기 위해 volume을 사용한다.
최초 volume을 생성할 때는 항상 비어있기 때문에 emptyDir이라고 부른다.
예를 들어 컨테이너 1번이 web 역할을 하고 2번이 백엔드라고 한다면, 웹서버로 받은 특정 파일을 마운트가 된 볼륨에 저장해두고 백엔드단도 볼륨을 마운트해놓으면 두 서버는 볼륨을 자신의 로컬에 있는 파일처럼 사용하기 때문에 두 서버가 서로 파일을 주고 받지 않아도 공유할 수 있다.
볼륨은 파드 안에 생성되므로 파드 삭제 시 죽어버리기 때문에 일시적인 데이터만 넣어두는 것을 권장한다.
```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-1
spec:
  containers:
  - name: container1 # 컨테이너1
    image: kubetm/init
    volumeMounts:
    - name: empty-dir # 볼륨 이름
      mountPath: /mount1 # 볼륨 마운트 경로
  - name: container2 # 컨테이너2
    image: kubetm/init
    volumeMounts:
    - name: empty-dir # 볼륨 이름
      mountPath: /mount2 # 볼륨 마운트 경로
  volumes: # 볼륨 정의
  - name : empty-dir
    emptyDir: {} # 볼륨 전략 지정
```
컨테이너 2개가 마운트 패스가 다르지만 같은 볼륨 정의를 사용하고 있기 때문에 결국 같은 볼륨을 마운트하고 있는 것이다.
즉, 각 컨테이너 내부에서는 지정한 path로 마운트가 되어 있지만 실질적으로는 볼륨을 보는 것이다.

### hostPath
![스크린샷 2022-07-06 오후 10 21 44](https://media.oss.navercorp.com/user/32533/files/30c73e7b-5d3e-4cde-8bb6-8b995180ce33)

pod들이 올라가 있는 노드를 볼륨으로 사용하기 때문에 파드가 죽어도 노드에 데이터가 남는다. 
하지만 파드 입장에서는 문제가 있다. 파드가 문제가 있어서 죽고 재생성 시 항상 같은 노드에 만들어진다는 보장이 없다. 따라서 다른 노드에 뜨게 되면 다른 노드에 저장된 볼륨을 마운트 할 수 없다.
하지만 굳이 방법을 찾는다면 다른 노드에서 똑같은 경로의 이름을 만들어 노드끼리 마운트하면 된다. 이건 쿠버네티스가 해주는 건 아니고 개발자가 직접 구성해야 한다.
자동화에 있어서 사람이 개입한다는 자체가 실수 발생의 여지가 있으므로 권장되지 않는다.

사용 용도
각각의 노드에는 각 노드 자신을 위해서 사용되는 시스템, 설정파일들이 있다.
파드 자신들이 할당된 노드(호스트)의 데이터를 읽어야 할 때 사용하면 된다.
```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-3
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
  containers:
  - name: container
    image: kubetm/init
    volumeMounts:
    - name: host-path
      mountPath: /mount1
  volumes:
  - name : host-path
    hostPath: # hostPath 전략 지정
      path: /node-v # 주의점 : 파드 생성 전에 해당 디렉토리가 만들어져있어야 한다. type을 DirectoryOrCreate로 주면 안만들어놔도 된다.
      type: Directory
```
다시 정리하면, 파드의 데이터 저장 용도가 아니라 노드의 데이터를 파드에서 쓰기 위한 용도다.

### PVC/PV
![스크린샷 2022-07-06 오후 10 25 15](https://media.oss.navercorp.com/user/32533/files/a7871b75-17ac-4af5-9e95-19492733a0f3)

파드의 영속성있는 볼륨을 제공하기 위한 방식이다.
아마존, git, 다른 서버, storageOS, 로컬 등에 연결할 수 있다.
쿠버네티스는 Volume 사용에 User 영역과 Admin 영역으로 나눴다.
Admin은 쿠버네티스를 운영하는 운영자고, User는 파드에 서비스를 만들고 배포를 관리하는 서비스 담당자다.
volume들의 종류는 많고 각각에 연결하기 위한 설정들은 모두 다르다.
따라서 이런것을 관리하는 Admin이 PV를 만들어 놓으면 User는 이걸 사용하기 위해 PVC를 만든다.

```yml
apiVersion: v1
kind: PersistentVolume # PV
metadata:
  name: pv-03
spec:
  capacity:
    storage: 2G
  accessModes:
  - ReadWriteOnce
  local: # 로컬 전략
    path: /node-v
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [k8s-node1]}
```
```yml
apiVersion: v1
kind: PersistentVolumeClaim # PVC
metadata:
  name: pvc-01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: "" # ""을 넣으면 현재 만들어진 PV 중 쿠버네티스가 알아서 판단하여 선택한다. 생략시 다른 방식으로 동작
```
```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-3
spec:
  containers:
  - name: container
    image: kubetm/init
    volumeMounts:
    - name: pvc-pv
      mountPath: /mount3
  volumes:
  - name : pvc-pv
    persistentVolumeClaim: # PVC 정의
      claimName: pvc-01 # pvc 연결
```

정리하면,

1. admin이 pv 정의
2. 사용자가 pvc 정의
3. 쿠버네티스가 pvc 내용에 맞는 적절한 pv에 연결
4. pod 생성 시 pvc 마운팅

여기까지 간단한 경우이다.  

### Dynamic Provisioning
![스크린샷 2022-07-07 오후 2 55 55](https://media.oss.navercorp.com/user/32533/files/b8241949-cffc-47b6-bdb9-ff33e51e36af)

Internal network를 사용하여 노드 자원을 이용해 volume을 관리하거나 External network로 외부 자원을 사용할 수 있다.  
관리자는 PV를 정의하고 사용자는 원하는 대로 PVC를 만들면 쿠버네티스가 적절한 연결을 해주고 이를 pod에서 사용한다.  
이런 방식으로 볼륨을 사용하면 볼륨이 필요할 때마다 pv를 만들어줘야 하고 원하는 pv와 연결하기 위해 스토리지와 accessMode를 맞춰야하는 번거로움이 있다.  

그래서 쿠버네티스에서는 Dynamic Provisioning이라고 해서 사용자가 PVC를 만들면 알아서 PV를 만들어주고 실제로 볼륨과 연결해주는 기능을 제공한다.  

모든 PV에는 파드처럼 각각에 상태가 존재한다. 상태를 통해서 지금 PV가 PVC에 연결된 상태인지, 에러가 났는지 등을 알 수 있다.  
<br>

![스크린샷 2022-07-07 오후 3 05 43](https://media.oss.navercorp.com/user/32533/files/fed156ec-b005-4ba4-bc38-6f43d66645ad)

사전 작업으로 dynamic provisioning을 지원해주는 스토리지 솔루션을 선택해서 설치한다.  
설치하면 서비스, 파드 등 여러 오브젝트가 생성되는데 가장 중요한건 StorageClass 오브젝트다.  
이를 통해 동적으로 PV를 만들게 된다.  
PVC를 만들 때 StorageClassName이라는 부분이 있는데 거기다가 만들어진 StorageClass를 넣으면 자동으로 PV가 만들어진다.  

<br>

### Status & ReclaimPolicy
![스크린샷 2022-07-07 오후 3 12 50](https://media.oss.navercorp.com/user/32533/files/f26b568e-be2d-49c9-8f29-9a3ed5ab774b)

최초 PV가 만들어지면 Available 상태다. PVC와 연결되면 Bound 상태로 변한다. Pod가 PVC를 사용해 구동될 때야 실제 volume이 만들어진다. 하지만 Dynamic Provisioning를 사용하면 자동으로 PV가 만들어질 때 바로 volume이 생성된다.  
Pod가 삭제되면 PVC, PV는 문제없다. PVC가 삭제되면 PV와 연결이 끊어지면서 PV가 Release 상태로 변한다.  
이 과정 중에 PV와 실제 데이터 간에 연결에 문제가 생기면 Failed상태로 변하기도 한다.  
PVC가 삭제되면 PV에 설정된 ReclaimPolicy에 따라 PV 상태가 달라진다.  
+ Retain 
    - PV 생성 시 ReclaimPolicy를 설정하지 않았다면 기본 정책
    - PVC 삭제 시 PV 상태가 Release로 변경    
    - 데이터가 보존되지만 재사용이 불가능해진다.
+ Delete
    - PVC를 지우면 PV도 지워진다.
    - StorageClass를 사용해서 자동으로 만든 PV인 경우의 기본 정책
    - volume 종류에 따라 실제 데이터가 삭제되기도 하고 안되기도 한다.
+ Recycle
    - deprecated 되었다.

## ConfigMap, Secret
![스크린샷 2022-07-06 오후 10 55 23](https://media.oss.navercorp.com/user/32533/files/27630a3a-98cc-4a33-b689-d2bb9569c746)

A서비스는 일반접근과 보안접근을 지원한다.
개발환경에서는 보안 접근을 해제할 수 있고 보안 접근 시 유저와 키를 세팅할 수 있다.
상용환경에서는 다시 보안 접근을 설정해야하고 유저와 키도 바꿔줘야 한다.

이 내용을 바꾼다는 것은 개발환경과 상용환경의 컨테이너 이미지를 각각 관리한다는 의미다.
이 값 몇가지 때문에 큰 용량의 이미지를 별도로 관리한다는 것은 부담스러운 일이다.

이 환경에 따라 변화는 값들을 관리할 수 있도록 하는 것이 ConfigMap과 Secret이다.
일반적인 상수들은 ConfigMap에서 관리하고 비밀값들은 Secret에서 관리한다.
파드 생성 시에 두 Object를 연결할 수 있는데 연결하면 컨테이너 환경 변수에 해당 데이터들이 들어가게 된다.
A 서비스에서는 이 환경변수를 읽어서 처리하면 된다.

<br>

두 Object를 만들 때 데이터로 상수를 넣을 수도 있고 파일로 넣을 수도 있다. 파일의 경우 볼륨 마운트로 연결해서 사용할 수도 있다.

### Env(Literal)
![스크린샷 2022-07-06 오후 10 57 56](https://media.oss.navercorp.com/user/32533/files/b26973dd-2ad8-49a1-959d-94a07467eb8b)

ConfigMap은 키 밸류값으로 구성되어 파드에 연결되어 사용된다.
Secret도 똑같은데 다른 점은 Value를 넣을 때 Base64로 인코딩을 해서 넣어야 한다.
파드로 주입될 때는 자동으로 디코딩되서 들어간다.
Secret은 메모리에 저장되고 ConfigMap은 용량 제한이 없지만 Secret은 1Mbyte 용량 제한이 있다.

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-dev
data: # 데이터 key-value형태로 정의
  SSH: 'false'
  User: dev
```
기본적으로 String 값으로 들어가기 때문에 boolean으로 넣고 싶다면 ''을 달아줘야 한다. 
```yml
apiVersion: v1
kind: Secret
metadata:
  name: sec-dev
data: # key-value 형태로 주입. 직접 넣을때는 base64로 인코딩해서 넣어야 한다.
  Key: MTIzNA==
```
```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
  - name: container
    image: kubetm/init
    envFrom:
    - configMapRef: # configMap 연결
        name: cm-dev
    - secretRef: # secret 연결
        name: sec-dev
```
해당 pod에 들어가서 env를 입력하면 확인 가능하다.

### Env(File)
![스크린샷 2022-07-06 오후 11 07 08](https://media.oss.navercorp.com/user/32533/files/826fa043-fb01-456d-8998-fda69b65d8a0)

파일을 통으로 담을 수 있는데 파일 이름이 키가 되고 내부값이 value가 된다.
파드의 환경변수에 넣을 때 키가 파일이름이 되어 이상할 수 있으므로 키를 재정의해서 컨텐츠를 넣을 수 있다.
```sh
kubectl create configmap [파일명] --from-file=경로
# secret은 파일 안의 내용이 base64로 인코딩되어 들어간다.
kubectl create secret generic [파일명] --from-file=경로

# 예시
kubectl create configmap cm-file --from-file=./file.txt
```
```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-file
spec:
  containers:
  - name: container
    image: kubetm/init
    env:
    - name: file-c # 키값 재정의
      valueFrom:
        configMapKeyRef:
          name: cm-file # 파일명
          key: file-c.txt # 키값
    - name: file-s
      valueFrom:
        secretKeyRef:
          name: sec-file
          key: file-s.txt
```
File의 경우 한번 주입하면 끝이기 때문에 파드에 들어간 이후 변경되어도 수정이 되지 않는다. 파드가 죽고 다시 뜨면 변경된다.

### Volume Mount(file)
![스크린샷 2022-07-07 오전 12 38 16](https://media.oss.navercorp.com/user/32533/files/06db30f8-fef9-43b4-86fd-7978319c8eea)

파일을 ConfigMap에 두는 것까지는 똑같다.
파드를 만들 때 컨테이너 안에 마운트 패스를 정의하고 패스 안에 파일을 마운팅한다.
```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-mount
spec:
  containers:
  - name: container
    image: kubetm/init
    volumeMounts:
    - name: file-volume
      mountPath: /mount
  volumes:
  - name: file-volume 
    configMap: # 볼륨에 configMap 연결
      name: cm-file # configMap 이름
```
마운팅되어 있어 파일이 수정되면 파드에 적용된다.

## Namespace, ResourceQuota, LimitRange
![스크린샷 2022-07-06 오후 11 24 06](https://media.oss.navercorp.com/user/32533/files/6d10f35a-1868-482e-b409-fe37b8be1330)

클러스터 내에서는 전체 사용가능한 자원이 한정되어 있다. 메모리, CPU 등등..  
클러스터 안에는 여러 Namespace 들을 만들 수 있고 Namespace 안에는 여러 Pod들을 만들 수 있다.
각 파드는 필요한 자원을 클러스터 자원을 공유해서 사용한다.
그런데 만약 하나의 네임스페이스에서 모든 자원을 사용해버리면 다른 쪽에서는 더이상 쓸 자원이 없어서 문제가 발생한다.
이런 문제를 해결하기 위해 ResourceQuota를 통해 네임스페이스마다 달아서 자원 할당량을 제한한다.
그런데 한 파드가 자원 사용량이 너무 커버리면 다른 파드들이 해당 네임스페이스에 들어오지 못하는 경우가 있는데 이때는 Limit Range를 통해 들어올 수 있는 파드의 크기를 제한할 수 있다.
두 오브젝트는 클러스터에도 달 수 있다.

### Namespace
![스크린샷 2022-07-06 오후 11 31 20](https://media.oss.navercorp.com/user/32533/files/ca6238f7-35ea-4382-b0c0-f7f3dd7dbf14)

+ 한 네임스페이스 안에는 같은 이름을 가진 파드를 생성할 수 없다. 즉, 한 네임스페이스 안에서 파드의 이름은 유일하다.
+ 타 네임스페이스 자원과 분리되어 관리된다.
+ 파드와 서비스가 다른 네임스페이스에 있다면 연결이 불가능하다.
+ 노드나 PV 같이 모든 네임스페이스에 공통해서 사용할 수 있는 경우도 있다.
+ 네임스페이스가 지워지면 안에 있는 자원도 모두 지워진다.
+ 파드마다 ip를 가지고 있는데 서로 다른 네임스페이스에 있는 파드로 접근하고자 한다면 접근은 가능하다. 하지만 네트워크 전략으로 제한이 가능하다.(보통은 이렇게 한다.)
+ 네임스페이스가 다르다고 해서 NodePort를 같은 포트로 사용할 수 없다.
+ 네임스페이스가 달라도 같은 노드일 때, host-path가 같다면 내용을 확인할 수 있는데 이는 기본적으로 파드의 권한이 root이기 때문인데 추후 파드 시큐리티 전략을 통해 권한 설정이 필요하다.

```yml
# 네임스페이스 생성
apiVersion: v1
kind: Namespace
metadata:
  name: nm-1
```
```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: nm-1 # 네임스페이스 지정
  labels:
    app: pod
spec:
  containers:
  - name: container
    image: kubetm/app
    ports:
    - containerPort: 8080
```
```yml
apiVersion: v1
kind: Service
metadata:
  name: svc-1
  namespace: nm-2 # 네임스페이스 지정
spec:
  selector:
    app: pod # 라벨을 선택했지만 네임스페이스가 pod-1와 다르므로 연결 X
  ports:
  - port: 9000
    targetPort: 8080
```

## ResourceQuota
![스크린샷 2022-07-06 오후 11 35 47](https://media.oss.navercorp.com/user/32533/files/65ce4889-ae29-4d05-95a7-7f4f059e6f95)

네임스페이스의 자원을 제한한다.

```yml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-1
  namespace: nm-3 # 네임스페이스 지정
spec:
  hard: # 네임스페이스 자원 제한량 지정
    requests.memory: 1Gi 
    limits.memory: 1Gi
```
```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  containers:
  - name: container
    image: kubetm/app
    resources: # 자원 명시
      requests:
        memory: 0.5Gi
      limits:
        memory: 0.5Gi
```
네임스페이스에 ResourceQuota가 등록되어 있다면 해당 네임스페이스에 들어가기 위해서는 반드시 파드의 자원을 명시하고 있어야 한다.
메모리 뿐만 아니라 cpu, memory, storage 등의 리소스와 Object 종류도 제한할 수 있다.

### LimitRange
![스크린샷 2022-07-07 오전 12 39 26](https://media.oss.navercorp.com/user/32533/files/0c45187a-6e8b-4506-9b38-fbdc46a4fa4d)

ResourceQuota가 네임스페이스의 자원을 제한했다면 LimitRange는 네임스페이스에 생성되는 파드의 자원을 제한한다.

```yml
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-5
  namespace: nm-1 #네임스페이스 지정
spec:
  limits:
  - type: Container
    min:
      memory: 0.1Gi # 최소
    max:
      memory: 0.5Gi # 최대
    maxLimitRequestRatio: # 최소 최대 비율
      # 예를 들어, 들어오는 파드의 request가 1Gi limit이 4Gi 라면
      # 4배의 비율을 가지고 있으므로 못들어온다.
      # 3배의 비율로 제한했기에
      memory: 3
    defaultRequest: # 파드에 request, limit 설정이 되어있지 않으면 default로 정의되어 들어간다.
      memory: 0.5Gi
    default:
      memory: 0.5Gi
```
한 네임스페이스에 여러 개의 LimitRange를 넣으면 오작동하므로 주의해야 한다.
