### ISSUE TITLE
[쿠버네티스] 컨트롤러 

### ISSUE THREAD

**Issue by backtony** [backtony/blog-code#3]
# 컨트롤러

+ Auto Healing
    - 파드가 죽거나 노드가 죽으면 파드를 다른 노드에 즉각 만들어준다.
+ Auto scaling
    - 파드의 리소스가 limit에 도달하면 파드를 하나 더 만들어 파드가 죽지 안도록 해준다.
+ Software Update
    - 여러 파드를 버전 업그레이드 해야 할 경우 컨트롤러로 한번에 할 수 있고 문제 발생시 롤백을 제공한다.
+ Job
    - 일시적인 작업이 필요한 경우 컨트롤러가 필요한 순간에 파드를 만들고 삭제한다.

<br>

## Replication Controller -> ReplicaSet
Replication Controller는 Deprecated 되었고 ReplicaSet을 사용한다.

### Template
![1](https://user-images.githubusercontent.com/68492475/188116971-b0326ab7-8971-43a8-b93d-65a77083b759.png)

컨트롤러와 파드는 서비스와 파드처럼 라벨과 셀럭터를 이용해 연결된다.  
컨트롤러를 만들 때 template으로 파드의 내용을 넣게 된다. 컨트롤러는 파드가 죽으면 template을 기반으로 파드를 새로 만들어 준다.  
이를 기반으로 업그레이드가 가능한데 template에 v2에 대한 내용을 업데이트 시키고 파드를 죽이면 새로 업그레이드 된 template을 사용하여 새로운 버전의 파드를 생성할 수 있다.

```yml
# 파드 하나 생성
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    type: web
spec:
  containers:
  - name: container
    image: kubetm/app:v1
    # 파드 삭제 시 기본 30초 후에 삭제되는데 0으로 바로 삭제되도록 지정
  terminationGracePeriodSeconds: 0
```
```yml
apiVersion: apps/v1
kind: ReplicaSet # ReplicaSet 컨트롤러 생성
metadata:
  name: replica1
spec:
  replicas: 1 # 1개의 파드를 지속적으로 유지
  selector:
    matchLabels: # 라벨로 앞서 생성한 파드 연결
      type: web
  template: # 템플릿 지정
    metadata:
      name: pod1
      labels: # 라벨을 지정해야 새로 만들어질 때 컨트롤러와 다시 연결된다.
        type: web
    spec: # 템플릿으로 생성될 스팩
      containers:
      - name: container
        image: kubetm/app:v1
      terminationGracePeriodSeconds: 0
```
template으로 만들어지는 파드 이름을 pod1로 하여 기존에 띄워진 파드 이름이랑 동일하게 작성했는데 실제로 새로운 파드는 설정과 달리 새로운 이름으로 뜨게 된다.  
수동으로 파드의 버전을 업데이트하고 싶다면 template의 스팩을 수정하고 기존 파드를 죽이면 된다.  
컨트롤러를 삭제하면 연결된 파드들도 모두 삭제되기 때문에 주의해야 하는데 컨트롤러만 죽이는 옵션도 있다.

### Replicas
![2](https://user-images.githubusercontent.com/68492475/188116991-3298753a-e3a6-4468-b41d-1020fde1bb54.png)

replicas 만큼 파드의 개수가 관리된다. 해당 숫자만큼의 파드가 관리되어야 하기 때문에 파드가 죽으면 새로 만들어준다.  
템플릿 기능을 통해 파드와 컨트롤러를 따로 만들지 않고 컨트롤러만 만들면 알아서 컨트롤러는 알아서 파드를 만든다.

#### Selector
![3](https://user-images.githubusercontent.com/68492475/188117016-615b15f1-74bc-494a-8067-cfbd4304f39a.png)

이 기능은 Replication Controller는 없고 ReplicaSet에만 있는 기능이다.  
deprecated된 Replication 컨트롤러는 키와 밸류가 같은 라벨에 연결된다.
반면 ReplicaSet에는 matchLabels라는 속성으로 key와 벨류를 매핑한다.(기존 라벨 매핑과 같은데 이름만 바뀜)  
matchExpressions이라는 속성이 있어 키와 밸류를 디테일하게 선택할 수 있다. 
![4](https://user-images.githubusercontent.com/68492475/188117049-a034447c-6ca9-4105-bd37-65d3d740d3ba.png)

+ matchExpressions : 여러 옵션이 있다.
    - Exists : 키가 일치하면 연결
    - DoesNotExist : 키가 다른 것만 연결
    - In : 키-밸류를 지정하여 둘다 매칭되는 것만 연결
    - NotIn : 키-밸류를 지정하여 키는 매칭되지만 value가 매칭되지 않는 것만 연결

일반적으로 matchLabels만 사용하지 matchExpression를 잘 사용하진 않는다.

```yml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica1
spec:
  replicas: 1
  selector:
    matchLabels: # 라벨 매핑
      type: web
      ver: v1
    matchExpressions: # 조건 매핑
        - {key: type, operator: In, values: [web]}
        - {key: ver, operator: Exists}
  template:
    metadata: # selector에 매핑한 라벨들을 반드시 포함하고 있어야 한다.
      labels:
        type: web # 포함
        ver: v1 # 포함
        location: dev
    spec:
      containers:
      - name: container
        image: kubetm/app:v1
      terminationGracePeriodSeconds: 0
```
matchLabels 사용 시 주의할 점은 셀렉터에서 매칭한 라벨은 반드시 템플릿에서 생성하는 파드의 라벨에 포함되어 있어야 한다는 것이다. 포함되지 않으면 생성할 수 없다.

<br>

## Deployment
일반적으로 4가지 배포 방식이 있다.

### ReCreate
![5](https://user-images.githubusercontent.com/68492475/188117078-a8fccd59-2ca8-4e41-911a-d606ec1bc470.png)

v1 파드를 우선적으로 죽인다. 따라서 순단이 발생한다. 그리고 v2 파드를 생성한다.
deployment를 띄우면 이에 따른 ReplicaSet이 뜨고 그리고 pod가 뜬다.
deployment에서 템플릿을 업데이트하면 기존 파드와 ReplicaSet이 죽고 새로운 ReplicaSet이 생성되어 파드가 뜨고 연결되는 것이다.  
간단하게 보면 위쪽 그림과 같고 실제로는 아래쪽 그림과 같다.   
아래 그림에는 service가 있지만 deployment만 띄우면 service는 없다. service는 따로 띄워야한다.

<img width="544" alt="5-1" src="https://user-images.githubusercontent.com/68492475/188117102-c2200734-f899-42e6-bfef-f9a1fb1ba2a0.png">

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  selector:
    matchLabels: # 아래쪽에 template의 라벨과 일치해야 한다.  selector가 template을 선택하는 구조이기 때문이다.
      type: app
  replicas: 2
  strategy: # 전략 지정
    type: Recreate 
  revisionHistoryLimit: 1 # 여러번 배포해도 1개의 ReplicaSet기록만 가지게 된다(현재것 포함 2개) 기본값 10
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
      - name: container
        image: kubetm/app:v1
      terminationGracePeriodSeconds: 10
```

### Rolling Update
![6](https://user-images.githubusercontent.com/68492475/188117131-9377f03f-baf9-4259-bd9d-2bdea43aff40.png)

v2 파드를 우선 하나 만든다. v1과 v2에 모두 서비스를 시작한다. 누군가는 v1에 누군가는 v2에 접속할 수 있다. 그리고 v1 파드를 하나 삭제하고 v2 파드를 하나 더 만든다. 이후에 v1을 모두 지운다.
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2
spec:
  selector:
    matchLabels:
      type: app2
  replicas: 2
  strategy: # 전략
    type: RollingUpdate 
  minReadySeconds: 10 # 보통 이 옵션을 지정하지 않는다. v1,v2 추가가 순식간에 진행되는데 이걸 보기위해 10초를 준것이다.
  template:
    metadata:
      labels:
        type: app2
    spec:
      containers:
      - name: container
        image: kubetm/app:v1
      terminationGracePeriodSeconds: 0
```

### Blue/Green
![7](https://user-images.githubusercontent.com/68492475/188117167-6d040977-b1d8-4d45-ade4-4c98bc21894f.png)

v1 파드는 서비스에서 연결되어 서비스되고 있다. 같은 양의 v2 파드를 만든다. 그리고 서비스의 라벨만 수정한다.  
v2에 문제가 발생하면 라벨만 수정해주면 되므로 롤백이 쉽다.
```yml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica1
spec:
  replicas: 2
  selector:
    matchLabels:
      ver: v1
  template:
    metadata:
      name: pod1
      labels:
        ver: v1
    spec:
      containers:
      - name: container
        image: kubetm/app:v1
      terminationGracePeriodSeconds: 0
```
BlueGreen은 전략을 지정하는게 아니기 때문에 ReplicaSet으로 만들고 라벨을 서비스에 붙이면 된다.  
그리고 새로운 ReplicaSet으로 업데이트 버전을 만들고 서비스에서는 새로운 라벨로 붙이면 된다.  

### Canary
2가지 방식이 있다.

![8](https://user-images.githubusercontent.com/68492475/188117184-9656b917-82a7-4580-a0e9-16690e220416.png)

ty:app 라벨로 service에 v1을 연결시켜 서비스중에 v2도 ty:app으로 하나 만들어서 연결시킨다. 문제가 발생하면 v2 컨트롤러의 replicas를 0으로 만들어버린다.
이는 불특정 다수에 대해 테스트하는 방식이다.

<br>

![9](https://user-images.githubusercontent.com/68492475/188117203-b3b19123-1f60-4864-8c28-be2e922a15cf.png)

각각의 서비스를 만들고 ingress controller로 유입되는 트래픽을 url path에 따라서 서비스에 연결해줄 수 있다.  
path 앞에 v2를 단 사람들은 새 버전을 사용하게 된다.  
예를 들어 글로벌 서비스에서 미국을 테스트로 사용하면 미국에서 접근하는 사람만 v2로 접근하도록 만들 수 있다.  
문제가 없으면 ingress controller를 수정하고 service1을 죽이면 된다.  

## DaemonSet
![10](https://user-images.githubusercontent.com/68492475/188117218-4c869b92-422c-4c74-84c6-2e0e64720c6d.png)

ReplicaSet은 파드를 스케줄러에 의존해서 자원 상황에 따라 파드를 분배한다.  
DaemonSet의 경우 노드의 자원과 상관없이 모든 노드에 1개씩 생성된다.  
대부분 모니터링 도구들이 이에 해당한다.  
쿠버네티스도 네트워킹 관리를 위해 각각 노드에 데몬셋으로 프록시 역할을 하는 파드를 만든다.  

![11](https://user-images.githubusercontent.com/68492475/188117235-cd652f38-4edf-48e9-a673-d0b629aa69a9.png)

데몬셋은 템플릿과 셀렉터가 있어서 모든 노드에 템플릿으로 파드를 만들고 셀럭터를 사용해 라벨로 데몬셋과 노드를 연결한다. nodeSelector를 지정하면 특정 노드에는 안 만들도록 할 수 있다.
```yml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-2
spec:
  selector: 
    matchLabels:
      type: app
  template: # 템플릿
    metadata:
      labels:
        type: app
    spec:
      nodeSelector: # 특정 노드에만 생성 -> 라벨 지정
        os: centos
      containers:
      - name: container
        image: kubetm/app
        ports:
        - containerPort: 8080
          hostPort: 18080 # 18080번으로 들어온 트래픽은 해당 파드의 8080으로 연결
```
데몬셋을 삭제하면 만들어진 파드들도 같이 삭제된다.

## Job, CronJob
![12](https://user-images.githubusercontent.com/68492475/188117245-cc555963-7506-4a4e-98c9-6c0ee38f9bc0.png)

노드가 죽으면 서비스가 유지될 수 없다. 컨트롤러에 의해 만들어진 파드들은 다른 노드에 재생성(recreate) 되기 때문에 서비스는 계속 유지된다.  
반면에 ReplicaSet에서 만들어진 파드가 일을 하지 않는다면 재시작(Restart)시켜주기 때문에 파드는 반드시 일을 하게 된다.  
반면 Job으로 만들어진 파드는 일을 하지 않으면 종료된다. 파드가 삭제되는 것은 아니고 자원을 사용하지 않고 중지된 것이다.  
CronJob은 이런 Job들을 주기적인 시간에 따라 생성하는 역할을 한다.  

### Job
![13](https://user-images.githubusercontent.com/68492475/188117260-9dd5a2ae-3267-44dc-8083-49a7651b21e5.png)

template에는 특정 작업만 하고 종료하는 pod를 정의한다.  
selector는 직접 만들지 않아도 job이 알아서 만들어준다.  
completions옵션을 주면 특정 개수의 파드를 순차적으로 실행시키고 모두 작업이 끝나면 job을 종료한다. paralleism 옵션을 주면 특정 개수만큼 파드가 생성된다.  activeDeadlineSeconds를 주면 특정 초 이후에 Job이 여전히 수행중이라면 중지하고 실행되고 있는 파드들은 모두 삭제한다. 앞으로 해야할 파드들도 실행되지 않는다.  
이는 보통 특정 시간동안 걸릴 작업을 만들었는데 어느정도 이후에도 완료가 안되면 죽여서 자원을 릴리즈해줄 때 사용한다.  

```yml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-2
spec:
  completions: 6 # 6개 파드
  parallelism: 2 # 2개씩 병렬
  activeDeadlineSeconds: 30 # 30초 이후에도 job이 완료안되면 죽여버림
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: container
        image: kubetm/init
        # 20초동안 일하게 만들기
        command: ["sh", "-c", "echo 'job start';sleep 20; echo 'job end'"]
      terminationGracePeriodSeconds: 0
```

### CronJob

<img width="551" alt="14" src="https://user-images.githubusercontent.com/68492475/188117277-e61a0a37-46ac-4f5e-9e76-032ffb13f0b2.png">

3가지 옵션이 있다.
+ Allow
    - 간격에 관계없이 사전에 만들어진 job이 동작중이어도 새로 job을 실행한다.
+ Forbid
    - 다음 간격에도 사전 job에 파드가 실행중이라면 현재 간격에서는 skip한다. 해당 pod가 종료되는 즉시 다음 job이 진행된다.
+ Replace
    - 다음 간격에도 기존 파드가 계속 동작중이면 job과 파드 모두 죽이고 새로 만든다.

```yml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job-2
spec:
  schedule: "*/1 * * * *" # 1분에 하나씩
  concurrencyPolicy: Replace 
  jobTemplate: # job 정의
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: container
            image: kubetm/init
            command: ["sh", "-c", "echo 'job start';sleep 140; echo 'job end'"]
          terminationGracePeriodSeconds: 0
```

# 컨트롤러 - 심화

## Stateless, Stateful Application
![1](https://user-images.githubusercontent.com/68492475/188117413-b7cc3740-5372-4ae7-b368-7f0a9c1ef992.png)

+ Stateless는 앱이 여러개 배포되더라도 다 똑같은 서비스 역할을 한다.  
+ Stateful은 각각의 앱마다 자신의 역할이 있다.
    - 예시로, Primary가 메인으로 죽으면 아비터가 감지해서 Secondary가 Primary로 승격시킬 수있는 각각 자신의 고유 역할을 갖는다.

Stateless 앱은 단순히 같은 서비스의 역할을 하는 앱을 복제해주면 되고 앱이름이 3이건 4이건 문제가 안되나, Stateful 앱은 아비터 역할을 하는 앱이 죽으면 반드시 아비터 역할을 하는 앱이 만들어져야 하고, 앱 이름도 고유 식별 요소이기 때문에 변경되면 안된다.  

stateless 앱은 사용자들이 접속하고 접속된 네트워크 트래픽은 분산되지만, stateful 앱은 대체로 내부 시스템들이 데이터베이스에 저장하기 위해 연결하기 때문에 특징에 맞게 트래픽이 들어가야 한다.  

쿠버네티스에서 이런 앱의 특징에 따라 활용할 수 있도록 나눠진 것은 다음과 같다.
+ Stateless : ReplicaSet
+ Stateful : StatefulSet

## StatefulSet 이해하기

![2](https://user-images.githubusercontent.com/68492475/188117445-3d34de86-91a6-40d9-b1ba-ad1b2460f3fe.png)

+ ReplicaSet
    - 이름이 랜덤으로 생성된다.
    - replicas를 늘리면 동시에 생성된다.
    - pod 삭제시 새로운 이름으로 생성된다.
    - replicas를 0으로 줄이면 동시에 삭제된다.
+ StatefulSet
    - 이름이 0부터 순차적으로 부여된다.
    - replicas를 늘리면 순차적으로 생성된다.
    - pod 삭제시 기존 이름으로 생성된다.
    - replicas를 0으로 줄이면 인덱스가 높은 순부터 순차적으로 삭제된다.

<Br>

![3](https://user-images.githubusercontent.com/68492475/188117468-9bd8223c-df76-4715-a8d3-ca7c33ceaa6f.png)

+ ReplicaSet
    - 파드에 Volume을 연결하려면 PVC를 직접 생성하고 template에 PVC를 지정하면 pod와 volume이 연결된다.
    - replicas가 증가하면 한 PVC에 모두 연결된다.
    - PVC가 노드1에 만들어졌다면 연결되는 파드도 노드1에 있어야 한다. 만약 노드2에 파드가 생성되면 PVC와 연결이 불가능하여 파드가 생성에 실패한다. 그래서 template 안에 셀럭터로 노드를 지정한다.
+ StatefulSet
    - template을 통해 pod가 만들어지고 volumeClaimTemplate을 사용하면 PVC가 동적으로 생성되어 pod와 연결된다.
    - replicas가 증가하면 파드가 추가될 때마다 새로운 PVC가 생성되어 연결된다.  pod가 삭제되면 같은 이름의 pod가 그대로 만들어지면서 붙어있던 pvc에 붙는다. 
    - 동적으로 파드와 PVC가 같은 노드에 만들어지기 때문에 모든 노드에 균등하게 배포된다.
    - replicas를 0으로 줄이면 파드를 순차적으로 삭제하지만 PVC는 삭제되지 않는다.

```yml
apiVersion: apps/v1
kind: StatefulSet # StatefulSet로 띄우기
metadata:
  name: stateful-pvc
spec:
  replicas: 1
  selector: 
    matchLabels:
      type: db2
  template: # replicas 증가시 띄울 파드 template
    metadata:
      labels:
        type: db2
    spec:
      containers:
      - name: container
        image: kubetm/app
        volumeMounts: # 볼륨 마운트
        - name: volume # 아래 template의 name과 일치시켜야 함
          mountPath: /applog
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates: # PVC 자동 생성 탬플릿이라고 생각하면 된다.
  - metadata:
      name: volume 
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1G
    # PVC 자동 생성 storageClass를 사용한 건데 이건 따로 사용할 on-promise solution을 설치해서 만들어야 한다.
      storageClassName: "fast" 
```
statefulSet의 경우 replicas가 올라가면 순차적으로 뒤에 숫자가 붙는다고 했다.  
pvc의 경우에는 name값-파드이름 형태로 생성된다.  

### Service LoadBalancing
![4](https://user-images.githubusercontent.com/68492475/188117506-ee035420-a713-4bda-b093-af325db6b63e.png)

각 서비스별로 파드를 나눠서 만들면 한 곳에서 문제가 생겨도 다른 쪽에는 문제가 생기지 않는다.  
그리고 외부에서 연결할 수 있도록 서비스를 각각 달아주고, 사용자들이 각 다른 도메인이름으로 접근하도록 하려고 한다면 일반적으로 각 path마다 서비스 ip를 이어줄 수 있는 L4, L7 스위치 장비가 필요하다.  
하지만 쿠버네티스에서는 Ingress 오브젝트가 그 역할을 대신한다.  

### Canary Upgrade
![스크린샷 2022-07-07 오후 7 21 32](https://user-images.githubusercontent.com/68492475/188117567-550bc069-9fb4-4e5c-903f-bd88bbc1f76c.png)

V1의 앱들이 서비스중인 상태에서 test할 V2를 구동시키고 Ingress로 두 서비스를 연결시키면 일부 트래픽만 v2로 보내도록 할 수 있다.  

### Ingress Controller
![스크린샷 2022-07-07 오후 7 22 40](https://user-images.githubusercontent.com/68492475/188117588-bc9b50a8-a5bf-430b-89a1-e024ec36f83e.png)

Ingress는 쿠버네티스가 설치되어 있다면 바로 만들 수 있다.  
host로 도메인이름을 넣을 수 있고 해당 도메인으로 들어오는 트래픽은 path에 따라 원하는 서비스로 연결하라는 것이 주 설정 내용이다.  
하지만 단순히 만들었다고 작동되는 것은 아니고 이 규칙을 실행할 구현체가 필요하다.  
쿠버네티스에서는 이 구현체를 만들기 위해 별도 플러그인을 설치해야 한다.  
플러그인들을 Ingress Controller라고 하고 대표적으로 NginX, Kong이 있다.  

![5](https://user-images.githubusercontent.com/68492475/188117609-41caaadc-474f-4445-bda5-3c3bd5102d08.png)

```sh
# nginx 쿠버 설치
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.0.0/deploy/static/provider/baremetal/deploy.yaml
```
NginX를 설치하면 nginx를 위한 네임스페이스가 생기고 이 안에 Deployment와 ReplicaSet이 만들어지면서 실제 Ingress의 구현체 Nginx 파드가 만들어진다.  
이 파드가 Ingress가 떠있는지를 확인해보고 있다면 그에 맞게 서비스에 연결한다.  
이 룰에 따라 해당 서비스에 트래픽이 전달되려면 외부에서 접근하는 사용자들의 트래픽은 nginx 파드를 지나야 하기 때문에 외부에서 접근가능한 서비스를 하나 만들어 nginx 파드에 연결해야 한다.  

직접 쿠버네티스를 설치했다면 노드 포트를 만들어서 외부에 연결할 수 있을 것이고, 클라우드 서비스를 이용했다면 로드밸런서를 만들어서 외부에 연결할 수 있을 것이다.  

```yml
apiVersion: networking.k8s.io/v1
kind: Ingress # ingress 타입
metadata:
  name: service-loadbalancing
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: / # /로 들어오는 요청은 svc-shopping로
        pathType: Prefix
        backend:
          service:
            name: svc-shopping
            port:
              number: 8080
      - path: /customer # /customer로 들어오는 요청은 svc-customer로
        pathType: Prefix
        backend:
          service:
            name: svc-customer
            port:
              number: 8080
      - path: /order # /order로 들어오는 요청은 svc-order로
        pathType: Prefix
        backend:
          service:
            name: svc-order
            port:
              number: 8080
```

```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
spec:
  ingressClassName: nginx
  rules:
  - host: www.app.com # host로 접근하면
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-v1 # svc-v1으로 트래픽 보내기
            port:
              number: 8080
```

```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-v2
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"  # 카나리 옵션 on
    nginx.ingress.kubernetes.io/canary-weight: "10" # 10% 트래픽만 이쪽으로 연결
spec:
  ingressClassName: nginx
  rules:
  - host: www.app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-v2
            port:
              number: 8080
```

```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-kr
  annotations:
    nginx.ingress.kubernetes.io/canary: "true" # 카나리 옵션 on
    nginx.ingress.kubernetes.io/canary-by-header: "Accept-Language" # header 키값
    nginx.ingress.kubernetes.io/canary-by-header-value: "kr" # header value값
    # 위 값에 매칭되는 요청은 아래 설정대로 트래픽 보내기
spec:
  ingressClassName: nginx
  rules:
  - host: www.app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-v2
            port:
              number: 8080
```
