### ISSUE TITLE
[spring oauth2] Spring Security Oauth2, clientRegistration

### ISSUE THREAD

**Issue by backtony** [backtony/blog-code#31]
# Spring Security
<img width="525" alt="1" src="https://user-images.githubusercontent.com/68492475/213962095-d44bd717-1a79-4447-96dc-34c1cde34f99.png">

과거에는 3개의 모듈이 하나의 프로젝트 안에 존재했지만, security 5로 업데이트 되면서 client support와 resource server는 security로 들어가게 되었고 authorization server는 다른 프로젝트로 진행되고 있다. 22년 11월 기준 Authorization server는 1.0.0 버전이 release 되었다.  

# OAuth 2.0 client 소개
+ OAuth 2.0 인가 프레임워크의 역할 중 인가서버 및 리소스 서버와의 통신을 담당하는 클라이언트의 기능을 필터 기반으로 구현한 모듈이다.
+ 간단한 설정만으로 OAuth 2.0 인증 및 리소스 접근 권한, 인가서버 엔드 포인트 통신 등의 구현이 가능하며 커스터마이징의 확장이 용이하다.

OAuth 2.0에서는 크게 2가지(Login, Client) API를 제공한다.

## OAuth 2.0 Login
+ 어플리케이션의 사용자를 외부 OAuth 2.0 Provider 나 OpenID Connect 1.0 Provider 계정으로 로그인할 수 있는 기능을 제공한다.
+ 글로벌 서비스 프로바이더인 “구글 계정으로 로그인”, “깃허브 계정으로 로그인” 기능을 Oauth 2.0 로그인을 구현해 사용할 수 있도록 지원한다.
+ OAuth 2.0 인가 프레임워크의 권한 부여 유형 중 Authorization Code 방식을 사용한다.

## OAuth 2.0 Client
+ OAuth 2.0 인가 프레임워크에 정의된 클라이언트 역할을 지원한다.
+ 인가 서버의 권한 부여 유형에 따른 엔드 포인트와 직접 통신할 수 있는 API 를 제공한다.
    - Client Credentials
    - Resource Owner Password Credentials
    - Refresh Token 
+ 리소스 서버의 보호자원 접근에 대한 연동 모듈을 구현 할 수 있다.

# OAuth 2.0 Client Fundamentals
## 의존성 추가
```groovy
implementation 'org.springframework.boot:spring-boot-starter-security'
implementation 'org.springframework.boot:spring-boot-starter-web'
implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
```

## 클라이언트 권한 부여 요청 시작
<img width="997" alt="2" src="https://user-images.githubusercontent.com/68492475/213962106-69b652e9-dd72-4447-bdb0-fb5e9c9bb8b0.png">

아래서 위로 보면 된다.  

1. 클라이언트가 인가서버로 권한 부여 요청을 하거나 토큰 요청을 할 경우 클라이언트 정보 및 엔드포인트 정보를 참조해서 전달한다.
2. application.yml 환경설정 파일에 클라이언트 설정과 인가서버 엔드포인트 설정을 한다.
3. 초기화가 진행되면 application.yml에 있는 클라이언트 및 엔드포인트 정보가 OAuth2ClientProperties 의 각 속성에 바인딩 된다.
4. OAuth2ClientProperties에 바인딩 되어 있는 속성의 값은 인가서버로 권한부여 요청을 하기 위한 ClientRegistration 클래스의 필드에 저장된다.
5. OAuth2Client 는 ClientRegistration 를 참조해서 권한부여 요청을 위한 매개변수를 구성하고 인가서버와 통신한다.

__위 과정을 스프링 security client 모듈이 다 해주기 때문에 개발자는 설정값만 입력해두면 된다.__  

## application.yml / OAuth2ClientProperties
<img width="1270" alt="3" src="https://user-images.githubusercontent.com/68492475/213962111-ed756ce8-b24e-42d6-9207-ba65eb36faf0.png">

application.yml에 설정값을 넣어주기만 하면 된다. spring.security.oauth2.client까지는 prefix에 해당한다. registration과 provider로 나뉘는데 registration은 client 설정을 의미하고 provider는 공급자 설정이다.  
OAuth2ClientProperties에는 registration이라는 필드가 map으로 되어있다. 아래 설정에서는 keycloak을 작성했는데 map의 key값으로 들어간다. 
```yml
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: authorization_code # oauth2.0 권한 부여 타입
            client-name: oauth2-client-app # 클라이언트 이름
            client-id: oauth2-client-app # 서비스 공급자에 등록된 클라이언트 아이디
            client-secret: secret # 서비스 공급자에게 등록된 클라이언트 비밀번호
            
            # spring security에서 내부적으로 초기화될 때 clientip/login/oauth2/code/{registrationId}로 정해진다.
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak # 인가서버에서 권한 코드 부여 후 클라이언트로 리다이렉트하는 위치

            # 클라이언트가 인가 서버에게 access token을 발급받을 떄 clientId, clientSecret을 전달하게 되는데 
            # 이때 clientId와 clientSecret을 전달하는 전송 방식 지정
            # 5가지 정도가 존재한다.
            client-authentication-method: client_secret_post # 클라이언트 자격증명 전송 방식
            scope: # 리소스 접근 제한 범위
              - openid
              - email
        provider: # 공급자(인가서버) 설정
          keycloak:
            issuer-uri: http://localhost:8080/realms/oauth2 # 서비스 공급자 위치 = base uri
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth # OAuth 2.0 권한 부여 엔드 포인트

            # 클라이언트가 리소스 서버에 데이터를 요청할 때 access token을 전달하는데 리소스 서버는 토큰을 검증한다.
            # 토큰은 이미 인가 서버에서 개인키로 서명이 되어있기 때문에 공개키로 검증해야하는데 공개키를 받아오는 엔드 포인트에 해당한다.
            jwk-set-uri: http://localhost:8080/realms/oaht2/protocol/openid-connect/certs # OAuth 2.0 JwkSetUri 엔드 포인트
            token-uri: http://localhost:8080/realms/oaht2/protocol/openid-connect/token # OAuth 2.0 토큰 엔드 포인트
            user-info-uri: http://localhost:8080/realms/oaht2/protocol/openid-connect/userinfo # OAuth 2.0 userinfo 엔드 포인트
            # 위의 uri는 각가에 따른 엔드 포인트를 작성하는 것이고 
            # user-name-attribute 사용자의 정보를 가져올 수 있는 key값을 적어준다. 
            # 해당 키값은 인가 서버마다 다르다. google의 경우는 sub가 키값이다. naver는 또 다르다.
            user-name-attribute: preferred_username # OAuth 2.0 사용자명을 추출하는 클레임명
```
registration에서 clientId, clientSecret, redirectUrl을 제외하면 나머지는 입력하지 않아도 기본적으로 알아서 찾아와서 적용한다. provider에서는 issuerUrl만 입력해도 알아서 찾아와서 적용한다.(알아서 찾아오는 과정은 아래서 clientRegistration 매핑 과정에서 설명)  

# ClientRegistration
+ OAuth 2.0 또는 OpenID Connect 1.0 Provider 에서 클라이언트의 등록 정보를 나타낸다.
+ ClientRegistration 은 OpenID Connect Provider의 설정 엔드포인트나 인가 서버의 메타데이터 엔드포인트를 찾아 초기화할 수 있다.
+ ClientRegistrations의 메소드를 사용하면 아래 예제처럼 편리하게 ClientRegistration 을 설정할 수 있다.
    - ClientRegistration clientRegistration = ClientRegistrations.fromIssuerLocation(“https://idp.example.com/issuer”).build(); 
        - http.. 내용은 인가 서버의 baseUrl
    - 위 코드는 200 응답을 받을 때까지 https://idp.example.com/issuer/.well-known/openid-configuration, https://idp.example.com/.well-known/oauth-authorization-server 에 차례대로 질의해본다.

<img width="904" alt="4" src="https://user-images.githubusercontent.com/68492475/213962118-cc743e07-642c-4a62-abec-2963241808ce.png">

clientRegistration은 client 등록 정보들을 가지고 있고, providerDetails(인가 서버)의 endpoint를 가지고 있다. providerDetails는 사용자 정보가 들어있는 userInfoEndpoint를 갖고 있다.  

## clientRegistration 필드 상세
+ registrationId : ClientRegistration을 식별할 수 있는 유니크한 ID
+ clientId : 클라이언트 식별자
+ clientSecret : 클라이언트 secret
+ clientAuthenticationMethod : provider에서 클라이언트를 인증할 때(인가 서버에서 access token을 발급해주기 위해서 클라이언트를 인증하는 과정에서 clientId와 clientSecret을 검증할 때) 사용할 메소드로서 basic, post, none (public 클라이언트) 을 지원한다.
    - basic : http basic 방식
    - post : http post 방식    
+ authorizationGrantType : OAuth 2.0 인가 프레임워크는 네 가지 권한 부여 타입을 정의하고 있으며 지원하는 값은 authorization_code, implicit, client_credentials, password다. 
+ redirectUriTemplate : 클라이언트에 등록한 리다이렉트 URL로, 사용자의 인증으로 클라이언트에 접근 권한을 부여하고 나면, 인가 서버가 이 URL로 최종 사용자의 브라우저를 리다이렉트시킨다.
+ Scopes : 인가 요청 플로우에서 클라이언트가 요청한 openid, 이메일, 프로필 등의 scope 
+ clientName : 클라이언트를 나타내는 이름으로 자동 생성되는 로그인 페이지에서 노출하는 등에 사용한다.
+ authorizationUri : authorization code 방식에서 1단계(임시 코드 발급)방식에서 인가 서버의 인가 엔드포인트 URI.
+ tokenUri : 인가 서버의 토큰 엔드포인트 URI.
+ jwkSetUri : JWT 포맷으로 토큰이 발행되었을 때, 인가 서버에서는 개인키로 서명하게 되고 이를 공개키로 검증할 수 있는데 이를 위해서는 JSON 웹 키 (JWK) 셋이 필요하고 이를 가져올 때 사용할 URI. 이 키 셋엔 ID 토큰의 JSON Web Signature (JWS) 를 검증할 때 사용할 암호키가 있으며, UserInfo 응답을 검증할 때도 사용할 수 있다.
+ configurationMetadata : OpenID Provider 설정 정보로서 application.properties 에 spring.security.oauth2.client.provider.[providerId].issuerUri를 설정했을 때만 사용할 수 있다.
+ (userInfoEndpoint)uri : 인증된 최종 사용자의 클레임/속성에 접근할 때 사용하는 UserInfo 엔드포인트 URI.(사용자 정보를 가져올 수 있는 uri)
+ (userInfoEndpoint)authenticationMethod : UserInfo 엔드포인트로 액세스 토큰을 전송할 때 사용할 인증 메소드. header, form, query 를 지원한다.
+ userNameAttributeName : UserInfo 응답에 있는 속성 이름으로, 최종 사용자의 이름이나 식별자에 접근할 때 사용한다.

## CommonOauth2Provider
+ OAuth 2.0 공급자 정보를 제공하는 클래스로서 글로벌 서비스 제공자 일부는 기본으로 제공되어진다.
    - GOOGLE, FACEBOOK, GITHUB, OKTA 등 대표적인 글로벌 기업들의 설정이 다 세팅되어있다.
    - 이런 글로벌을 사용할 경우에는 properties 설정에서 registration의 clientId, clientSecret값만 주면 나머지는 자동으로 전부 세팅된다.
+ Client ID 와 Client Secret 는 별도로 application.properties 에 작성해야 한다. 
+ Naver 나 Kakao 와 같은 국내 공급자 정보는 위의 모든 항목을 수동으로 작성해서 사용해야 한다. 
+ 클라이언트 기준인 Registration 항목과 서비스 제공자 기준인 Provider 항목으로 구분하여 설정한다.
+ application.properties 가 아닌 Java Config 방식으로 ClientRegistration 등록을 설정 할 수 있다.
+ ClientRegistration 객체를 생성할 수 있는 빌더 클래스를 반환한다.

## ClientRegistration 매핑 과정
<img width="1325" alt="5" src="https://user-images.githubusercontent.com/68492475/213962125-04809528-8aa7-43ee-b7f4-447b3e84b209.png">

1. ClientRegistration 필드에 들어가는 값들은 인가 서버에 등록되어 있다. spring security oauth 2.0 client가 기동되게 되면 해당 정보들을 인가 서버로부터 가지고 온다. 
2. OAuth2ClientRegistrationRepositoryConfiguration에서는 ClientRegistrationRepository 빈이 존재하지 않을 경우 빈을 생성한다.
3. OAuth2ClientPropertiesRegistrationAdapter에서 CleintRegistrations의 메서드를 사용해서 인가 서버에 rest로 통신을 해서 client의 메타 데이터 정보들을 가져온다.
4. 응답 값을 사용해서 ClientRegistration 필드를 매핑한다.(1차 매핑 완료)
5. application.properties에 별도로 설정을 하게 되면 application.properties 값이 덮어쓰면서 설정된다.

# ClientRegistrationRepository
+ ClientRegistrationRepository 는 OAuth 2.0 & OpenID Connect 1.0 의 `ClientRegistration 저장소 역할`을 한다.
+ __클라이언트 등록 정보는 궁극적으로 인가 서버가 저장하고 관리하는데 이 레포지토리는 인가 서버에 일차적으로 저장된 클라이언트 등록 정보의 일부를 검색하는 기능을 제공한다.__
+ __스프링 부트 2.X 자동 설정은 spring.security.oauth2.client.registration.[registrationId] 하위 프로퍼티를 ClientRegistration 인스턴스에 바인딩하며, 각 ClientRegistration 객체를 ClientRegistrationRepository 안에 구성한다.__
+ ClientRegistrationRepository 의 디폴트 구현체는 InMemoryClientRegistrationRepository 다.
    - __clientRegistartion 자체가 많지는 않기 때문에 운영환경에서 메모리로 관리해도 문제 없다.__
+ 자동 설정을 사용하면 ClientRegistrationRepository 도 ApplicationContext 내 @Bean 으로 등록하므로 필요하다면 원하는 곳에 의존성을 주입할 수 있다.

<img width="1223" alt="6" src="https://user-images.githubusercontent.com/68492475/213962132-ca5a3095-583b-4e66-828a-f781efb96155.png">

application.yml에 등록하면 자동으로 등록되지만 위와 같이 직접 등록할 수도 있다.  
위와 같이 `ClientRegistration.withRegistrationId` api를 사용해서 정의하면 직접 다 입력해줘야 하지만, `ClientRegistrations.fromIssuerLocation` api를 사용하면 인가 서버로부터 정보를 가져와서 채워넣기 때문에 registration 필수값(registrationId, clientId, clientSecret, 경우에 따라 redirectUri)만 넣어주면 된다.
