### ISSUE TITLE
[spring oauth2] OAuth 2.0 Client - oauth2Client

### ISSUE THREAD

**Issue by backtony** [backtony/blog-code#33]
# OAuth 2.0 Client - oauth2Client
## OAuth2ClientConfigurer 초기화 이해
<img width="1296" alt="1" src="https://user-images.githubusercontent.com/68492475/214221582-0ea016ac-b407-4e0d-badf-b277d894da2b.png">

OAuth2ClientConfigurer는 AuthorizationCodeGrantConfigurer의 init과 configure 메서드를 호출한다. 위에 3개는 인가 서버에서 code를 받는데 사용되고 마지막 하나는 code를 사용해서 access token을 발급받는데 사용된다.

```java
@Configuration(proxyBeanMethods = false)
public class CustomOAuth2ClientConfig {
   @Bean
   public SecurityFilterChain oauth2SecurityFilterChain(HttpSecurity http) throws Exception {
    http.authorizeRequests((requests) -> requests.anyRequest().authenticated())
        // .oauth2Login(Customizer.withDefaults());
        .oauth2Client(Customizer.withDefaults());
    return http.build();
   }
}
```
+ oauth2Login
    - 클라이언트가 인가서버로부터 인가를 받고 최종 사용자의 인증처리까지 처리한다.
+ oauth2Client
    - 클라이언트가 인가서버로부터 인가까지만 처리한다.
    - 인증을 위해서는 개발자가 따로 코드를 작성해야 한다.

### 주요 클래스
<img width="1235" alt="2" src="https://user-images.githubusercontent.com/68492475/214221593-17625019-4dcc-49a3-afc1-9db219ccd236.png">

+ OAuth2AuthorizedClient
    + OAuth2AuthorizedClient 는 인가받은 클라이언트를 의미하는 클래스다. 
    + 최종 사용자(리소스 소유자)가 클라이언트에게 리소스에 접근할 수 있는 권한을 부여하면, 클라이언트를 인가된 클라이언트로 간주한다
    + OAuth2AuthorizedClient 는 AccessToken, RefreshToken, ClientRegistration (클라이언트)와 권한을 부여한 최종 사용자인 Principal을 묶어 준다.(가지고 있다)
        + OAuth2AuthorizedClient 의 AccessToken 을 사용해서 리소스 서버의 자원에 접근 할 수 있으며 인가서버와의 통신으로 토큰을 검증할 수 있다
        + OAuth2AuthorizedClient 의 ClientRegistration 과 AccessToken 을 사용해서 UserInfo 엔드 포인트로 요청할 수 있다
+ OAuth2AuthorizedClientRepository
    - OAuth2AuthorizedClientRepository 는 다른 웹 요청이 와도 동일한 OAuth2AuthorizedClient 를 유지하는 역할을 담당한다. 
    - OAuth2AuthorizedClientService 에게 OAuth2AuthorizedClient 의 저장, 조회, 삭제 처리를 위임한다.(OAuth2AuthorizedClient 관리 역할을 service에게 위임한다.)
+ OAuth2AuthorizedClientService
    - OAuth2AuthorizedClientService 는 어플리케이션 레벨에서 OAuth2AuthorizedClient 를 관리(저장, 조회, 삭제)하는 일이다.
+ OAuth2AuthorizationCodeGrantFilter
    + Authorization Code Grant 방식으로 권한 부여 요청을 지원하는 필터(인가까지만 지원하는 필터로 사용자 인증은 진행하지 않음)
    + 인가서버로부터 리다이렉트 되면서 전달된 code 를 인가서버의 Access Token 으로 교환한다.
    + OAuth2AuthorizedClientRepository 를 사용하여 OAuth2AuthorizedClient 를 저장 후 클라이언트의 Redirect Uri 로 이동한다

## OAuth2AuthorizedClientManager
<img width="1306" alt="3" src="https://user-images.githubusercontent.com/68492475/214221609-93baa849-72d1-49fa-aa9b-96ed0137aec1.png">

+ OAuth2AuthorizedClient(권한 획득을 한(인가 받은, access token을 받은) 클라이언트) 를 전반적으로 관리하는 인터페이스
    - 구현체로는 HttpServletRequest의 컨텍스트인 DefaultOAuth2AuthorizedClientManager과 HttpServletReuqest의 컨텍스트 외부에서 작동할 때 사용되는 AuthorizedClientServiceOAuth2AuthorizedClientManager가 있다.
+ OAuth2AuthorizedClientProvider를 필드로 갖으면서 이는 OAuth 2.0 클라이언트에 권한 부여한다.
    - Client Credentials Flow
    - Resource Owner Password Flow
    - Refresh Token Flow
+ OAuth2AuthorizedClientService 나 OAuth2AuthorizedClientRepository 에 OAuth2AuthorizedClient 저장을 위임한 후 OAuth2AuthorizedClient 최종 반환
+ 사용자 정의 OAuth2AuthorizationSuccessHandler 및 OAuth2AuthorizationFailureHandler 를 구성하여 성공/실패 처리를 변경할 수 있다.
+ invalid_grant 오류로 인해 권한 부여 시도가 실패하면 이전에 저장된 OAuth2AuthorizedClient가 OAuth2AuthorizedClientRepository 에서 제거된다

주요 클래스와 OAuth2AuthorizedClientManager를 알아봤다. 결과적으로는 OAuth2AuthorizedClientManager를 사용하면 주요클래스들을 사용해서 인가를 구현할 수 있다. OAuth2AuthorizedClientManager를 사용하여 로그인 구현을 하기 위해서는 다음과 같은 flow을 생각하면 된다.  

1. DefaultOAuth2AuthorizedClientManager 빈 생성 및 파라미터 초기 값들을 정의한다
2. 권한 부여 유형에 따라 요청이 이루어도록 application.yml 설정을 조정한다
3. /oauth2Login(controller로 만들어놓은 url) 주소로 권한 부여 흐름을 요청한다
4. DefaultOAuth2AuthorizedClientManager 에게 권한 부여를 요청한다
5. 권한 부여가 성공하면 OAuth2AuthorizationSuccessHandler 를 호출하여 인증 이후 작업을 진행한다.  DefaultOAuth2AuthorizedClientManager 의 최종 반환값인 OAuth2AuthorizedClient를 OAuth2AuthorizedClientRepository 에 저장한다
6. OAuth2AuthorizedClient 에서 Access Token 을 참조하여 /userinfo 엔드포인트 요청으로 최종 사용자 정보를 가져온다
7. 사용자 정보와 권한을 가지고 인증객체를 만든 후 SecurityContext 에 저장하고 인증을 완료한다
8. 인증이 성공하면 1~7 번의 과정을 커스텀 필터를 만들어서 처리하도록 한다. 

OAuth2AuthorizedClientManager를 사용해서 인가처리하기 위해서는 빈으로 만들어주어야 한다.
```java
@Configuration
public class AppConfig {

    @Bean
    public OAuth2AuthorizedClientManager authorizedClientManager(ClientRegistrationRepository clientRegistrationRepository,
                                                                 OAuth2AuthorizedClientRepository authorizedClientRepository) {

        OAuth2AuthorizedClientProvider authorizedClientProvider =
                // 허용할 방식을 설정하는 것으로 4가지 방식을 지원한다.
                OAuth2AuthorizedClientProviderBuilder.builder()
                        .authorizationCode()
                        .clientCredentials()
                        .password()
                        .refreshToken()
                        .build();

        DefaultOAuth2AuthorizedClientManager authorizedClientManager =
                new DefaultOAuth2AuthorizedClientManager(
                        clientRegistrationRepository, authorizedClientRepository);
        authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

        return authorizedClientManager;
    }
}
```

#### 흐름
__인가 흐름__  
<img width="1320" alt="4" src="https://user-images.githubusercontent.com/68492475/214221654-23f7a551-64e9-427d-a6a1-0ba082c98c18.png">

1. 요청을 받아 인가에 필요한 정보를 OAuth2AuthorizedRequest 객체에 담아 OAuth2AuthorizedClientManager에 넘긴다.
2. OAuth2AuthorizedClient가 존재한다면(이미 인가 받은적이 있다면) 리턴하고 없다면 인가작업을 시작한다.
3. 실패하면 OAuth2AuthorizationFailureHandler에서 후속처리를 하고 성공하면 OAuth2AccessTokenResponse 값으로 응답을 받아 OAuth2AuthorizedClient에 저장하고 OAuth2AuthorizationSuccessHandler에서 후속처리를 진행한다.

__인증 흐름__  

<img width="1320" alt="5" src="https://user-images.githubusercontent.com/68492475/214221662-010ef342-0cc8-4879-9c44-784d3da36e1c.png">

#### yml 설정
```yml
spring:
    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        clientId: oauth2-client-app
                        clientSecret: dXf021lMWuZ9kZafqxZn230MvVEdROIo
                        clientName: oauth2-client-app
                        authorizationGrantType: password # password 방식 정의
                        scope: openid,profile
                        clientAuthenticationMethod: client_secret_basic
                        provider: keycloak

                provider:
                    keycloak:
                        issuerUri: http://localhost:8080/realms/oauth2
                        authorizationUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
                        jwkSetUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
                        tokenUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
                        userInfoUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
                        userNameAttribute: preferred_username
```

#### Manager 빈 설정
```java
@Configuration
public class AppConfig {

    @Bean
    public DefaultOAuth2AuthorizedClientManager auth2AuthorizedClientManager(ClientRegistrationRepository clientRegistrationRepository,
                                                                             OAuth2AuthorizedClientRepository clientRepository){

        OAuth2AuthorizedClientProvider oauth2AuthorizedClientProvider =
                OAuth2AuthorizedClientProviderBuilder.builder()
                        .authorizationCode()
                        .password()
                        .clientCredentials()
                        .refreshToken()
                        .build();

        DefaultOAuth2AuthorizedClientManager oAuth2AuthorizedClientManager =
                new DefaultOAuth2AuthorizedClientManager(clientRegistrationRepository,clientRepository);
        oAuth2AuthorizedClientManager.setAuthorizedClientProvider(oauth2AuthorizedClientProvider);

        // password 방식이므로 추가 작업이 필요
        oAuth2AuthorizedClientManager.setContextAttributesMapper(contextAttributesMapper());

        return oAuth2AuthorizedClientManager;

    }

    private Function<OAuth2AuthorizeRequest, Map<String, Object>> contextAttributesMapper() {
        return oAuth2AuthorizeRequest -> {
            // password 방식이므로 request에서 username과 password를 추출하고 context에 넣어주도록 한다.
            // 이는 토큰 요청시 인가 서버에 전달하게 된다.
            Map<String,Object> contextAttributes = new HashMap<>();
            HttpServletRequest request = oAuth2AuthorizeRequest.getAttribute(HttpServletRequest.class.getName());
            String username = request.getParameter(OAuth2ParameterNames.USERNAME);
            String password = request.getParameter(OAuth2ParameterNames.PASSWORD);

            if(StringUtils.hasText(username) && StringUtils.hasText(password)){

                contextAttributes.put(OAuth2AuthorizationContext.USERNAME_ATTRIBUTE_NAME,username);
                contextAttributes.put(OAuth2AuthorizationContext.PASSWORD_ATTRIBUTE_NAME,password);
            }
            return contextAttributes;
        };
    }
}
```

#### controller 설정
```java
@Controller
public class LoginController {

    @Autowired
    private DefaultOAuth2AuthorizedClientManager oAuth2AuthorizedClientManager;

    @Autowired
    private OAuth2AuthorizedClientRepository oAuth2AuthorizedClientRepository;

    @GetMapping("/oauth2Login")
    public String oauth2Login(Model model, HttpServletRequest request, HttpServletResponse response) {
        
        // 익명 사용자 인증 객체
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();

        // 인가에 필요한 정보를 담은 객체 생성
        // 해당 정보를 앞서 config에서 정의한 곳에서 request와 response를 추출해서 사용하게 된다.
        OAuth2AuthorizeRequest authorizeRequest = OAuth2AuthorizeRequest
                .withClientRegistrationId("keycloak")
                .principal(authentication)
                .attribute(HttpServletRequest.class.getName(), request)
                .attribute(HttpServletResponse.class.getName(), response)
                .build();

        // 기본값으로 DefaultOAuth2AuthorizedClientManager의 생성자에 
        // 기본 default SuccessHandler가 들어가있어서 인가받은 authorizedClient는 OAuth2AuthorizedClientRepository에 저장된다.
        // 여기서 커스텀해주는 이유는 그냥 어떻게 커스텀해서 넣는지 확인해보기 위함
        // 아래 코드는 DefaultOAuth2AuthorizedClientManager 생성자에 있는 successHandler 코드 그대로 가져옴
        OAuth2AuthorizationSuccessHandler successHandler = (authorizedClient, principal, attributes) -> {
            oAuth2AuthorizedClientRepository
                .saveAuthorizedClient(authorizedClient, principal,
                    (HttpServletRequest)attributes.get(HttpServletRequest.class.getName()),
                    (HttpServletResponse)attributes.get(HttpServletResponse.class.getName()));
        };

        oAuth2AuthorizedClientManager.setAuthorizationSuccessHandler(successHandler);

        // 인가 요청을 진행하고 인가받은 클라이언트 반환 : 인가 완료
        OAuth2AuthorizedClient authorizedClient = oAuth2AuthorizedClientManager.authorize(authorizeRequest);

        // 인증 처리 시작
        if(authorizedClient != null){
            // 인가받은 클라이언트 정보 추출
            ClientRegistration clientRegistration = authorizedClient.getClientRegistration();
            OAuth2AccessToken accessToken = authorizedClient.getAccessToken();
            // 인증 처리에 필요한 객체 생성
            OAuth2UserRequest oAuth2UserRequest = new OAuth2UserRequest(clientRegistration,accessToken);

            // 인증 처리에 사용되는 userService 생성
            OAuth2UserService<OAuth2UserRequest,OAuth2User> oAuth2UserService = new DefaultOAuth2UserService();
            
            // 인증 처리 요청
            OAuth2User oAuth2User = oAuth2UserService.loadUser(oAuth2UserRequest);

            // 권한을 커스텀하고 싶은경우 Mapper 사용 -> 기본적으로 권한은 SCOPE_email 형태인데 prefix를 붙이면 SYSTEM_SCOPE_email이 된다.
            // 토큰을 만들때 oAuth2User.getAuthorities() 대신 grantedAuthorities를 넣어주면 된다.
            // SimpleAuthorityMapper authorityMapper = new SimpleAuthorityMapper();
            // authorityMapper.setPrefix("SYSTEM_");
            // Set<GrantedAuthority> grantedAuthorities = authorityMapper.mapAuthorities(oAuth2User.getAuthorities());

            // 토큰을 만들어주고 securityContext에 넣어주면 인증이 완료된다.
            OAuth2AuthenticationToken oAuth2AuthenticationToken =
                new OAuth2AuthenticationToken(oAuth2User, oAuth2User.getAuthorities(), clientRegistration.getRegistrationId());

            SecurityContextHolder.getContext().setAuthentication(oAuth2AuthenticationToken);

            // 타임리프 매핑
            model.addAttribute("oAuth2AuthenticationToken", oAuth2AuthenticationToken);
        }


        return "home";
    }


    @GetMapping("/logout")
    public String logout(Authentication authentication, HttpServletResponse response, HttpServletRequest request) {
        SecurityContextLogoutHandler logoutHandler = new SecurityContextLogoutHandler();
        logoutHandler.logout(request, response, authentication);

        return "redirect:/";
    }
}
```

### Client Credentials 방식으로 구현하기
<img width="1286" alt="6" src="https://user-images.githubusercontent.com/68492475/214221686-52c56246-7325-459e-bef5-28d2551366e6.png">

흐름은 password방식과 유사하고 처리하는 클래스들만 다르다.  

#### yml 설정
```yml
spring:
    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        clientId: oauth2-client-app
                        clientSecret: dXf021lMWuZ9kZafqxZn230MvVEdROIo
                        clientName: oauth2-client-app
                        authorizationGrantType: client_credentials # 방식 변경
                        # client_credentials 방식은 사용자 역할이 없고 server to server로 사용되기 때문에 scope이 필요 없다.
                        # scope: openid,profile
                        clientAuthenticationMethod: client_secret_basic
                        provider: keycloak

                provider:
                    keycloak:
                        issuerUri: http://localhost:8080/realms/oauth2
                        authorizationUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
                        jwkSetUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
                        tokenUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
                        userInfoUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
                        userNameAttribute: preferred_username
```

Manager 빈 설정은 password방식에서 username, password 세팅해주는 코드를 제외하면 되고, controller에서는 인증하는 코드를 제외하고 인가까지만 진행하면 된다.  
인가받은 클라이언트에서 토큰을 꺼내서 다른 서버로 통신하거나 검증할때 사용한다. 

### Refresh Token 방식으로 구현하기
<img width="1316" alt="7" src="https://user-images.githubusercontent.com/68492475/214221698-20ad915b-97e4-417e-9817-e8a507b7271e.png">

이 또한 전의 과정과 유사하나 access Token이 만료되었을 때 다시 인증과정을 거치지 않고 refresh Token을 사용해서 access Token을 발급받아 진행한다.

#### yml 설정
```yml
spring:
    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        clientId: oauth2-client-app
                        clientSecret: dXf021lMWuZ9kZafqxZn230MvVEdROIo
                        clientName: oauth2-client-app
                        authorizationGrantType: password # password 방식을 사용하면 된다.
                        scope: openid,profile
                        clientAuthenticationMethod: client_secret_basic
                        provider: keycloak

                provider:
                    keycloak:
                        issuerUri: http://localhost:8080/realms/oauth2
                        authorizationUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
                        jwkSetUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
                        tokenUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
                        userInfoUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
                        userNameAttribute: preferred_username
```

#### Manager 빈 등록
```java
@Configuration
public class AppConfig {

    @Bean
    public DefaultOAuth2AuthorizedClientManager auth2AuthorizedClientManager(ClientRegistrationRepository clientRegistrationRepository,
                                                                             OAuth2AuthorizedClientRepository clientRepository){

        OAuth2AuthorizedClientProvider oauth2AuthorizedClientProvider =
                OAuth2AuthorizedClientProviderBuilder.builder()
                        .authorizationCode()
                        // access token 재발급 기간 설정, 기본값은 60초, (현재시간 > 토큰 만료시간 - 60초) 이면 만료로 판단
                        // 3600초로 커스텀했으므로 (현재시간 > 토큰 만료시간 - 3600초) 이면 만료로 판단 : 테스트용이므로 빨리 만료시키려고 이렇게 둠
                        // access token 생명주기는 인가 서버에서 정해준다.
                        // 보통은 건드릴 일이 없는데 refresh를 테스트해보기 위해서 커스텀
                        .password(passwordGrantBuilder -> passwordGrantBuilder.clockSkew(Duration.ofSeconds(3600)))
                        .refreshToken(refreshTokenGrantBuilder -> refreshTokenGrantBuilder.clockSkew(Duration.ofSeconds(3600)))
                        .clientCredentials()
                        .build();

        DefaultOAuth2AuthorizedClientManager oAuth2AuthorizedClientManager =
                new DefaultOAuth2AuthorizedClientManager(clientRegistrationRepository,clientRepository);

        oAuth2AuthorizedClientManager.setAuthorizedClientProvider(oauth2AuthorizedClientProvider);
        oAuth2AuthorizedClientManager.setContextAttributesMapper(contextAttributesMapper());

        return oAuth2AuthorizedClientManager;

    }

    private Function<OAuth2AuthorizeRequest, Map<String, Object>> contextAttributesMapper() {
        return oAuth2AuthorizeRequest -> {
            Map<String,Object> contextAttributes = new HashMap<>();
            HttpServletRequest request = oAuth2AuthorizeRequest.getAttribute(HttpServletRequest.class.getName());
            String username = request.getParameter(OAuth2ParameterNames.USERNAME);
            String password = request.getParameter(OAuth2ParameterNames.PASSWORD);

            if(StringUtils.hasText(username) && StringUtils.hasText(password)){

                contextAttributes.put(OAuth2AuthorizationContext.USERNAME_ATTRIBUTE_NAME,username);
                contextAttributes.put(OAuth2AuthorizationContext.PASSWORD_ATTRIBUTE_NAME,password);
            }
            return contextAttributes;
        };
    }
}
```

#### Controller
```java
@Controller
public class LoginController {

    @Autowired
    private DefaultOAuth2AuthorizedClientManager oAuth2AuthorizedClientManager;

    @Autowired
    private OAuth2AuthorizedClientRepository oAuth2AuthorizedClientRepository;

    private Duration clockSkew = Duration.ofSeconds(3600);

    private Clock clock = Clock.systemUTC();

    @GetMapping("/oauth2Login")
    public String oauth2Login(Model model, HttpServletRequest request, HttpServletResponse response) {

        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();

        OAuth2AuthorizeRequest authorizeRequest = OAuth2AuthorizeRequest
                .withClientRegistrationId("keycloak")
                .principal(authentication)
                .attribute(HttpServletRequest.class.getName(), request)
                .attribute(HttpServletResponse.class.getName(), response)
                .build();

        OAuth2AuthorizedClient authorizedClient = oAuth2AuthorizedClientManager.authorize(authorizeRequest);

        // 원래는 위에 코드까지만 해도 작동한다. 아래 코드부터는 refresh 토큰을 사용하는 것을 확인하기 위함
        // 위에서 authorize 메서드로 인가된 클라이언트를 만들었으나 accessToken 유효기간이 5분인데 manager 빈을 등록할때 5분남은 경우 만료로 설정했으므로
        // 아래 코드에서 다시 authorize 메서드를 호출하면 refresh 토큰을 사용한 로직으로 인가를 진행하게 된다.
        // 권한 부여 타입을 변경하지 않고 토큰 재발급
        if (authorizedClient != null && hasTokenExpired(authorizedClient.getAccessToken())
                && authorizedClient.getRefreshToken() != null) {
            authorizedClient = oAuth2AuthorizedClientManager.authorize(authorizeRequest);
        }

        model.addAttribute("AccessToken", authorizedClient.getAccessToken().getTokenValue());
        model.addAttribute("RefreshToken", authorizedClient.getRefreshToken().getTokenValue());

        return "home";

    }

    private boolean hasTokenExpired(OAuth2Token token) {
        return this.clock.instant().isAfter(token.getExpiresAt().minus(this.clockSkew));
    }


    @GetMapping("/logout")
    public String logout(Authentication authentication, HttpServletResponse response, HttpServletRequest request) {
        SecurityContextLogoutHandler logoutHandler = new SecurityContextLogoutHandler();
        logoutHandler.logout(request, response, authentication);

        return "redirect:/";
    }
}
```

### Filter 기반으로 구현하기
<img width="1286" alt="8" src="https://user-images.githubusercontent.com/68492475/214221709-9b24427b-b047-468c-9fda-032c8d85bc4e.png">

요청을 필터로 받는 것을 제외하고는 앞선 것과 흐름은 같다. 
이전 로직들을 필터로만 옮기면 된다.  

#### Manager 빈 등록
```java
@Configuration
public class AppConfig {

    @Bean
    public DefaultOAuth2AuthorizedClientManager authorizedClientManager(ClientRegistrationRepository clientRegistrationRepository,
                                                                        OAuth2AuthorizedClientRepository authorizedClientRepository) {

        OAuth2AuthorizedClientProvider authorizedClientProvider =
                OAuth2AuthorizedClientProviderBuilder.builder()
                        .authorizationCode()
                        .clientCredentials()
                        .password(passwordGrantBuilder -> passwordGrantBuilder.clockSkew(Duration.ofSeconds(3600)))
                        .refreshToken(refreshTokenGrantBuilder -> refreshTokenGrantBuilder.clockSkew(Duration.ofSeconds(3600)))
                        .build();

        DefaultOAuth2AuthorizedClientManager authorizedClientManager =
                new DefaultOAuth2AuthorizedClientManager(
                        clientRegistrationRepository, authorizedClientRepository);
        authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);
        authorizedClientManager.setContextAttributesMapper(contextAttributesMapper());

        return authorizedClientManager;
    }

    private Function<OAuth2AuthorizeRequest, Map<String, Object>> contextAttributesMapper() {
        return authorizeRequest -> {
            Map<String, Object> contextAttributes = Collections.emptyMap();
            HttpServletRequest servletRequest = authorizeRequest.getAttribute(HttpServletRequest.class.getName());
            String username = servletRequest.getParameter(OAuth2ParameterNames.USERNAME);
            String password = servletRequest.getParameter(OAuth2ParameterNames.PASSWORD);
            if (StringUtils.hasText(username) && StringUtils.hasText(password)) {
                contextAttributes = new HashMap<>();

                // `PasswordOAuth2AuthorizedClientProvider` requires both attributes
                contextAttributes.put(OAuth2AuthorizationContext.USERNAME_ATTRIBUTE_NAME, username);
                contextAttributes.put(OAuth2AuthorizationContext.PASSWORD_ATTRIBUTE_NAME, password);
            }
            return contextAttributes;
        };
    }
}
```

#### Filter 생성
```java
public class CustomOAuth2LoginAuthenticationFilter extends AbstractAuthenticationProcessingFilter {

    public static final String DEFAULT_FILTER_PROCESSES_URI = "/oauth2Login/**";
    private OAuth2AuthorizedClientRepository authorizedClientRepository;
    private DefaultOAuth2AuthorizedClientManager oAuth2AuthorizedClientManager;
    private OAuth2AuthorizationSuccessHandler authorizationSuccessHandler;

    private OAuth2AuthorizationFailureHandler authorizationFailureHandler;

    private Duration clockSkew = Duration.ofSeconds(3600);

    private Clock clock = Clock.systemUTC();

    public CustomOAuth2LoginAuthenticationFilter(DefaultOAuth2AuthorizedClientManager oAuth2AuthorizedClientManager, OAuth2AuthorizedClientRepository oAuth2AuthorizedClientRepository) {
        super(DEFAULT_FILTER_PROCESSES_URI);
        this.oAuth2AuthorizedClientManager = oAuth2AuthorizedClientManager;
        this.authorizedClientRepository = oAuth2AuthorizedClientRepository;

        this.authorizationSuccessHandler = (authorizedClient, authentication, attributes) ->
                authorizedClientRepository
                        .saveAuthorizedClient(authorizedClient, authentication,
                                (HttpServletRequest) attributes.get(HttpServletRequest.class.getName()),
                                (HttpServletResponse) attributes.get(HttpServletResponse.class.getName()));
        this.oAuth2AuthorizedClientManager.setAuthorizationSuccessHandler(authorizationSuccessHandler);
    }

    @Override
    public Authentication attemptAuthentication(HttpServletRequest request, HttpServletResponse response) throws AuthenticationException, IOException, ServletException {

        Authentication principal = SecurityContextHolder.getContext().getAuthentication();
        
        // mvc에서는 기본적으로 principal이 null이 될 수 없고 익명사용자로 넘어오는데
        // 익명사용자를 만들어주는 필터는 usernamePasswordFilter 뒤쪽에 있다.
        // 이 필터는 usernamePasswordFilter 앞쪽에 있기 때문에 
        // 익명사용자가 아니라 null이 들어오므로 익명 사용자를 만들어줘야 한다.
        if (principal == null) {
            principal = new AnonymousAuthenticationToken("anonymous","anonymousUser", AuthorityUtils.createAuthorityList("ROLE_ANONYMOUS"));
        }

        OAuth2AuthorizeRequest authorizeRequest = OAuth2AuthorizeRequest
                .withClientRegistrationId("keycloak")
                .principal(principal)
                .attribute(HttpServletRequest.class.getName(), request)
                .attribute(HttpServletResponse.class.getName(), response)
                .build();

        // 인가 처리
        // 인가가 완료되면 successHandler가 동작하게 되는데 기본적으로는 authorizedClientRepository에 AuthorizedClient가 저장된다.
        // 저장되는 방식에 따라 세션, map, jdbc 에 저장되는데 map으로 사용될 경우, map의 키값이 principal로 사용된다.
        // 여기서는 인가까지만 진행되므로 map의 경우 익명사용자가 principal로 들어가게 된다. 이 경우에는 인증까지 처리된 이후 다시 호출해서 principal을 인증된 사용자로 처리해줘야 한다.
        OAuth2AuthorizedClient oAuth2AuthorizedClient = oAuth2AuthorizedClientManager.authorize(authorizeRequest);

        // 인증 처리
        if(oAuth2AuthorizedClient != null) {
            ClientRegistration clientRegistration = oAuth2AuthorizedClient.getClientRegistration();
            OAuth2AccessToken accessToken = oAuth2AuthorizedClient.getAccessToken();
            OAuth2RefreshToken refreshToken = oAuth2AuthorizedClient.getRefreshToken();

            OAuth2UserService oAuth2UserService = new DefaultOAuth2UserService();
            OAuth2User oauth2User = oAuth2UserService.loadUser(new OAuth2UserRequest(
                    oAuth2AuthorizedClient.getClientRegistration(), accessToken));

            SimpleAuthorityMapper simpleAuthorityMapper = new SimpleAuthorityMapper();
            Collection<? extends GrantedAuthority> authorities = simpleAuthorityMapper.mapAuthorities(oauth2User.getAuthorities());
            OAuth2AuthenticationToken oAuth2AuthenticationToken = new OAuth2AuthenticationToken(oauth2User, authorities, clientRegistration.getRegistrationId());

            // map의 경우 인증된 사용자를 principal로 해주기 위해 다시 handler 호출
            authorizationSuccessHandler.onAuthorizationSuccess(oAuth2AuthorizedClient, oAuth2AuthenticationToken, createAttributes(request, response));

            return oAuth2AuthenticationToken;
        }

        return null;

    }

    // DefaultOAuth2AuthorizedClientManager 에서 가져옴
    private static Map<String, Object> createAttributes(HttpServletRequest servletRequest, HttpServletResponse servletResponse) {
        Map<String, Object> attributes = new HashMap<>();
        attributes.put(HttpServletRequest.class.getName(), servletRequest);
        attributes.put(HttpServletResponse.class.getName(), servletResponse);
        return attributes;
    }
}
```

#### security 설정에 필터 등록
```java
@Configuration(proxyBeanMethods = false)
public class OAuth2ClientConfig {

    @Autowired
    private DefaultOAuth2AuthorizedClientManager authorizedClientManager;
    @Autowired
    private OAuth2AuthorizedClientRepository authorizedClientRepository;

    @Bean
    SecurityFilterChain oauth2SecurityFilterChain(HttpSecurity http) throws Exception {
        http.authorizeRequests((requests) -> requests.antMatchers("/","/oauth2Login","/logout").permitAll().anyRequest().authenticated());
        http
                .oauth2Client()
                .and()
                .addFilterBefore(customOAuth2LoginAuthenticationFilter(), UsernamePasswordAuthenticationFilter.class)
                ;
        return http.build();
    }
    public CustomOAuth2LoginAuthenticationFilter customOAuth2LoginAuthenticationFilter() throws Exception {
        CustomOAuth2LoginAuthenticationFilter customOAuth2LoginAuthenticationFilter =
                new CustomOAuth2LoginAuthenticationFilter(authorizedClientManager,authorizedClientRepository);

        // filter가 처리를 다 완료했다면(인증 + 인가) 어딘가로 redirect 해준다.
        customOAuth2LoginAuthenticationFilter.setAuthenticationSuccessHandler((request, response, authentication) -> {
            response.sendRedirect("/home");
        });
        return customOAuth2LoginAuthenticationFilter;
    }
}
```

## @RegisteredOAuth2AuhtorizedClient
+ 파라미터를 OAuth2AuthorizedClient 타입 인자로 리졸브해준다
OAuth2AuthorizedClientArgumentResolver 에서 요청을 가로채어 유형별로 권한 부여 흐름을 실행하도록 한다.
+ 이 방법은 OAuth2AuthorizedClientManager 나 OAuth2AuthorizedClientService 로 OAuth2AuthorizedClient 에 접근하는 것보다 편리하다.

```java
@GetMapping("/")
public String index(@RegisteredOAuth2AuthorizedClient("keycloak") OAuth2AuthorizedClient authorizedClient) {
    OAuth2AccessToken accessToken = authorizedClient.getAccessToken();
    return "index";
}
```
