### ISSUE TITLE
[쿠버네티스] Pod

### ISSUE THREAD

**Issue by backtony** [backtony/blog-code#4]
# Pod

## Lifecycle 
![1](https://user-images.githubusercontent.com/68492475/188117827-6c2e7452-a330-45d1-9fc2-e5ec87dc8eb7.png)

+ Status : 상태 [true, false]
    - Phase : 파드의 전체 상태를 대표  
        - Pending : 파드 최초 상태
            - 본 컨테이너가 기동되기 전에 초기화 시켜야하는 내용을 담는 initContainer가 있을 수 있다.
            - 파드가 어느 노드에 올라갈 지 지정
            - 컨테이너에 이미지 다운
        - Running : 컨테이너 기동
            - 컨테이너가 기동 중에 문제가 발생하면 컨테이너 상태는 waiting이 되지만 파드는 컨테이너가 running이라고 간주한다. 이때 conditions에 ContainerReady와 ready를 false로 정의되는데 이를 확인하면 된다. 만약 원활하게 돌아간다면 True가 된다.
            - 주의할 것이 서비스가 계속 운영이 되어야 하는 경우 True를 유지해야 한다. 파드의 상태가 Running이더라도 내부 컨테이너 상태가 Running이 아닐 수 있기 때문에 파드 뿐만 아니라 컨테이너의 상태도 모니터링 해줘야 한다.
        - Succeeded, Failed
            - Job이나 CronJob으로 생성된 경우 자신의 일을 수행중일 때는 Running 중이지만 일을 마치면 Succeeded, Failed로 갈리게 된다.
            - 이때 파드의 컨디션 값이 변하게 되는데 성공이건 실패건간에 ContinaerReady, Ready 값이 false로 바뀐다. 
        - Unknown
            - Pending, Running 중에 통신 장애가 발생하면 파드가 Unknown 상태로 변한다.
            - 통신 장애가 빨리 해결되면 기존 상태로 변경되지만 지속적이라면 Failed로 변경된다.
    - Conditions : 파드가 생성되면서 실행하는 단계들과 상태를 알려주는 속성
    - Reason : Conditions의 세부 내용
        - status가 false인 경우 이유 표기
    - State : 파드 안의 컨테이너마다 상태를 대표하는 속성
        - Reason : state의 이유를 표기
    
전체적인 개요도는 다음과 같다. 

![2](https://user-images.githubusercontent.com/68492475/188117848-7b65b0ee-bd3e-40e1-8865-8cf42f185c20.png)

## ReadinessProbe, LivenessProbe
![3](https://user-images.githubusercontent.com/68492475/188117865-545002ad-6cb5-43ba-b975-baff8d4ec930.png)

서비스에서 노드1과 노드2의 파드에 요청을 분산해서 전달하다가 노드2가 죽어버렸다고 해보자.  
그렇다면 auto healing 기능을 통해 노드3에 파드가 새로 뜨게 된다.  
근데 파드와 서비스가 연결되었지만 앱이 아직 뜨는 과정에 있어서 사용자는 에러를 보게 될 수 있다.  
이 때 ReadinessProbe 옵션을 주면 이런 문제를 피할 수 있다.  
ReadinessProbe가 앱이 구동되기 전까지는 서비스와 연결되지 않도록 해준다.  
즉, 제대로 뜨기 전까지 해당 pod는 제외된다고 보면 된다.  

<br>

![4](https://user-images.githubusercontent.com/68492475/188117879-9e30f4b9-33bc-4b82-8071-977bad0a89ee.png)

앱이 잘 돌아가다가 갑자기 앱이 장애가 날 수 있다.  
예를 들면, 톰캣은 잘 도는데 그 안에 앱이 메모리 문제 등으로 인해 톰캣은 잘 돌지만 그 위에 앱이 문제가 될 수 있다.  
톰캣 프로세스를 보고 있는 파드 입장에서는 계속 Running 상태로 유지되기 때문에 이쪽으로 오는 트래픽에는 문제가 생긴다.  
이때 이 문제를 감지하는게 LivenessProbe이다.  
해당 앱에 문제가 생기면 파드를 재실행하여 잠깐의 에러는 발생하겠지만 지속적인 에러를 방지할 수 있다.  

<br>

![5](https://user-images.githubusercontent.com/68492475/188117898-d3fa69b0-3079-487c-a73f-508800d33556.png)

위와 같은 옵션들을 줄 수 있다.  

<br>

![6](https://user-images.githubusercontent.com/68492475/188117920-a2f81612-56cf-40e8-913e-848501d448f3.png)

ReadinessProbe 옵션만 먼저 보자.  
파드는 만들어질 때 노드가 스케줄되고 이미지가 다운받아지면서 파드와 컨테이너 상태는 러닝상태가 되지만, 세팅해준 probe가 성공하기 전 까지는 ContainerReady와 Ready 상태가 false가 된다.  
이 상태가 유지되면 파드가 NotReadyAddr로 간주하여 서비스에 연결하지 않는다.  
옵션 세팅에 따르면 컨테이너 상태가 Running이 되면 최초 5초는 지연하다가 이후에는 ready.txt 파일이 있는지 확인해보고 10초 이후에 다시 체크한다. 3번 성공을 확인하면 Condition의 상태가 true로 변경되고 서비스에 연결된다.  
```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-readiness-exec1
  labels:
    app: readiness  
spec:
  containers:
  - name: readiness
    image: kubetm/app
    ports:
    - containerPort: 8080	
    readinessProbe: # 파드의 readinessProbe 옵션 정의
      exec:
        command: ["cat", "/readiness/ready.txt"]
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 3
    volumeMounts:
    - name: host-path
      mountPath: /readiness
  volumes:
  - name : host-path
    hostPath:
      path: /tmp/readiness
      type: DirectoryOrCreate
  terminationGracePeriodSeconds: 0
```

<br>

![7](https://user-images.githubusercontent.com/68492475/188117937-e926ef8e-7348-4d38-9305-a459b4dbe5d1.png)

LivenessProbe 옵션을 보자.  
최초 뜨고 난 이후 5초 이후 요청을 보내고 10초 간격으로 보낸다. 3회 실패 시 문제가 있다고 판단하여 파드를 재시작해버린다.  
```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-liveness-httpget1
  labels:
    app: liveness
spec:
  containers:
  - name: liveness
    image: kubetm/app
    ports:
    - containerPort: 8080
    livenessProbe: # livenessProbe 옵션 정의
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
  terminationGracePeriodSeconds: 0
```

<br>

샘플
```yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-probe
  labels:
    app: probe
spec:
  containers:
  - name: probe
    image: kubetm/app
    ports:
    - containerPort: 8080	
    readinessProbe:
      exec:                   # command 내용으로 점검
        command: ["cat", "/readiness/ready.txt"]   
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 3     # 3번 성공시 Service와 연결됨
    livenessProbe:
      httpGet:                # HttpGet 메소드로 점검
        path: /health         # 체크할 경로
        port: 8080            # 체크할 Port
      initialDelaySeconds: 5  # 최초 5초 후에 LivenessProbe 체크를 시작함
      periodSeconds: 10       # 10초마다 LivenessProbe 체크
      failureThreshold: 3      # 3번 실패시 Pod Restart
```

## Node Scheduling

![8](https://user-images.githubusercontent.com/68492475/188117960-c0c360bb-6c84-4488-aa5e-5ce2fa4618c2.png)

+ 아무 세팅을 하지 않으면 스케줄러는 자원이 가장 많은 곳으로 파드를 할당한다.  
+ NodeName 을 명시하면 해당 노드에 생성되지만 노드가 죽을 수 있어서 사용하진 않는다.
+ NodeSelector를 사용해서 라벨을 명시하면 해당 라벨을 명시한 노드 중에서 자원이 많은 곳에 할당 된다. 매칭되는 라벨이 없으면 파드가 할당되지 않는다.
+ NodeAffinity는 키만 설정하고 노드에 할당한다. 매칭되지 않으면 자원이 가장 많은 곳으로 넣을 수 있는 옵션을 줄 수도 있다.
+ Pod Affinity는 둘 이상의 파드를 같은 노드로 넣을 때 사용한다. 우선 하나의 파드를 노드에 넣고, 두 번째 파드부터는 pod Affinity 속성에 앞서 들어간 파드의 라벨을 명시하면 된다.
+ Pod Anti-Affinity는 마스터와 슬레이브가 같은 노드에 들어갔을 때 노드가 죽으면 문제가 되기 때문에 다른 노드에 할당하기 위해 사용된다. 마스터가 우선 노드에 들어가고 슬레이브를 Anti-Affinity 옵션으로 마스터의 라벨을 주면 된다.
+ Toleration / Taint는 특정 노드에 아무 파드나 할당되지 않도록 설정할 때 사용한다. 노드에 Taint를 달아준다.(Taint를 식별하는 라벨을 주고 effect 옵션으로 Noschedule을 주면 스케줄링으로 배치되지 않는다.) Pod를 만들 때는 Toleration을 준다. key, value가 Taint의 라벨과 같아야 하고 effect의 종류도 같아야 한다.
    - 주의해야할 것이 알아서 파드가 taint가 있는 노드로 가는 것이 아니다. taint는 들어올 수 있는 파드를 정의해준 것이고 toleration은 taint 노드에 들어갈 수 있는 자격을 명시해준 것이다. 따라서 toleration이 붙은 파드는 다른 노드에 갈 수도 있는 것이다. 즉, toleration이 붙은 파드에는 nodeSelector로 taint가 붙은 노드를 명시해줘야 한다.
    - effect
        - Noschedule : 스케줄러를 타지 않는다. Taint가 붙은 노드에 아무 파드나 들어올 수 없다.
        - PreferNoSchedule : 가급적 스케줄링이 안되게 하나 정 안되면 조건이 안맞아도 Taint가 붙은 노드에 파드가 할당될 수 있다.
        - NoExecute : 앞선 effect는 이미 노드에 파드가 있다면 그대로 두지만 이 옵션의 경우 이미 노드에 파드가 있다면 그것을 죽인다. 만약 기존에 있는 파드가 effect가 NoExecute면 삭제가 되지 않는다. 만약 NoExecute지만 tolerationSeconds 옵션을 줬다면 해당 시간이 지나면 죽는다.
    - operator
        - Exists
        - Equal

<br>

### MatchExpressions
```yml
apiVersion: v1
kind: Pod
metadata:
 name: pod-match-expressions1
spec:
 affinity:
  nodeAffinity:
  # required 옵션은 라벨이 매칭되는 노드가 없다면 생성되지 못하고 Pending 상태로 유지된다.
   requiredDuringSchedulingIgnoredDuringExecution:   
    nodeSelectorTerms:
    - matchExpressions:
      -  {key: kr, operator: Exists}
 containers:
 - name: container
   image: kubetm/app
 terminationGracePeriodSeconds: 0
```

### Prefered
```yml
apiVersion: v1
kind: Pod
metadata:
 name: pod-preferred
spec:
 affinity:
  nodeAffinity:
    # 선호도를 기준으로 노드 지정
    # 보통 자원이 많이 남은곳으로 간다. 예로 50, 30 자원이 남아있으면 50쪽 노드로 간다.
    # 하지만 30인 쪽의 라벨을 세팅하고 가중치를 30으로 주면 60이되어 그쪽 노드로 간다.
   preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1 # 가중치
      preference:
       matchExpressions: # key가 ch인 노드에 가중치 부여
       - {key: ch, operator: Exists}
 containers:
 - name: container
   image: kubetm/app
 terminationGracePeriodSeconds: 0
```

### Affinity
```yml
apiVersion: v1
kind: Pod
metadata:
 name: web1
 labels:
  type: web1
spec:
 nodeSelector: # a-team:1 노드로 파드를 할당
  a-team: '1'
 containers:
 - name: container
   image: kubetm/app
 terminationGracePeriodSeconds: 0
```
```yml
apiVersion: v1
kind: Pod
metadata:
 name: server1
spec:
 affinity:
  podAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:      
   # 라벨 키가 a-team인 노드들 중에서 라벨이 matchExpressions에 매핑되는 파드가 있는 노드를 찾아서 거기다가 파드 생성
   - topologyKey: a-team # 노드 라벨 키가 a-team인 것들 중에서만 찾음
     labelSelector:
      matchExpressions:
      -  {key: type, operator: In, values: [web1]} 
 containers:
 - name: container
   image: kubetm/app
 terminationGracePeriodSeconds: 0
```
만약 해당하는 파드가 위치한 노드를 못 찾으면 Pending 상태로 되다가 찾으면 Running 상태로 변경된다.  

### Anti-Affinity
```yml
apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
     type: master
spec:
  nodeSelector:
    a-team: '1'
  containers:
  - name: container
    image: kubetm/app
  terminationGracePeriodSeconds: 0
```
```yml
apiVersion: v1
kind: Pod
metadata:
 name: slave
spec:
 affinity:
  podAntiAffinity:
   requiredDuringSchedulingIgnoredDuringExecution: 
   # a-team 키를 가진 노드 중에서 matchExpressions에 매칭되는 라벨이 있는 파드의 노드를 피해서 파드 생성  
   - topologyKey: a-team
     labelSelector:
      matchExpressions:
      -  {key: type, operator: In, values: [master]}
 containers:
 - name: container
   image: kubetm/app
 terminationGracePeriodSeconds: 0
```

### Toleration
노드에 taint가 걸려있다고 가정
```yml
apiVersion: v1
kind: Pod
metadata:
 name: pod-with-toleration
spec:
 nodeSelector:
  gpu: no1
 tolerations:
 - effect: NoSchedule # taint와 일치해야함
   key: hw # taint와 일치해야함
   operator: Equal
   value: gpu # taint와 일치해야함
 containers:
 - name: container
   image: kubetm/app
 terminationGracePeriodSeconds: 0
```
NoExecute의 경우
```yml
apiVersion: v1
kind: Pod
metadata:
 name: pod1-with-no-execute
spec:
 tolerations:
 - effect: NoExecute
   key: out-of-disk
   operator: Exists
   tolerationSeconds: 30
 containers:
 - name: container
   image: kubetm/app
 terminationGracePeriodSeconds: 0
```
